### ISSUE TITLE
can not delete ssh connection

### ISSUE THREAD

**Issue by yangqun** [wavetermdev/waveterm#100]
can not delete ssh connection or modify ssh port if you have already saved it.

**Comment by sawka** [comment]
To delete an SSH connection, go to "edit connection settings" and then click on "archive connection".  you can't modify an existing connection's user, host, or port.  so once you archive it, you can recreate it with the right port.

**Comment by yangqun** [comment]
thanks very much.

**Comment by sawka** [comment]
Moved the delete button to be more visible in v0.5.1
