### ISSUE TITLE
[Bug]: .bash_profile not being properly sourced

### ISSUE THREAD

**Issue by trashyms** [wavetermdev/waveterm#1015]
### Feature description

Ability to set a script to be executed any time a shell is started.

**Comment by esimkowitz** [comment]
This is already possible with your shell's RC files, can you elaborate on what you want Wave to do differently?

**Comment by trashyms** [comment]
.bash_profile is never executed automatically

has to be sourced manually

**Comment by esimkowitz** [comment]
This sounds more like a bug... Will take a look

**Comment by esimkowitz** [comment]
@trashyms just to confirm, if you run `echo $SHELL` from Wave, what value do you get and is it the same as if you run it from the default Terminal?

**Comment by trashyms** [comment]
Thanks for the suggestion.

My wave version is version 0.8.11 202410110234

And I do get the same result for echo $SHELL 
in both termilal default application
and in wave interpreter.

Sometimes new terminal just freeze: impossible to enter any command.

**Comment by esimkowitz** [comment]
What leads you to suspect that your .bash_profile isn't running? Can you try adding an echo statement in your .bash_profile to see if it logs anything to your console?

**Comment by trashyms** [comment]
What lead me to think that .bash_profile isn't run are:

  - my prompt shell is the default and not my custom I hace in other apps
  - I don't have my alias and other commands 
  - after running manually I get my customized prompt and my alias and other installed tools
   
Thanks for your concern.

**Comment by esimkowitz** [comment]
To confirm, which version of macOS are you on? Did you try adding the echo statement to your .bash_profile to see if it got run at all? I wonder if it's running and then unsetting. Also, is this on your local machine or a remote machine?

**Comment by trashyms** [comment]
I am using MacOS Monterey 12.7.6 (21H1320) on a 15 inches mid-2015 MacBook Pro.

I did add the echo command and it's give me the same result on wave and others terminal application.

It's running on my local machine. 


Seems to be what you suggesting: unsetting before complete shell initaalization.

Because after I run the .bash_profile manualy, everything is working completety normally.
