### ISSUE TITLE
[Feature]: Option to Change Focused Block Border Color

### ISSUE THREAD

**Issue by ShadowArcanist** [wavetermdev/waveterm#1020]
### Feature description

Right now, the block you are focused on has a green border, and there’s no way to change this color. Even if you use different tab background colors like blue or red, the focused block stays green, which doesn’t look good.

I would like an option to change the border color of the focused block.

![image](https://github.com/user-attachments/assets/0d50da29-f8f2-4953-89a0-41621d1515c3)

### Implementation Suggestion

I would like to change the border color through the `settings.json` file, similar to how we change the `window:bgcolor`.

**Comment by sawka** [comment]
there is actually a "secret" meta key that will set this on a per block basis `frame:bordercolor:focused`.  you can try `wsh setmeta frame:bordercolor:focused=red` (or any "#rrggbb" color).  that doesn't do it global or system-wide though.  it should be an easy-enough change to add.  probably makes sense to add to the tab backgrounds configuration.

**Comment by ShadowArcanist** [comment]
@sawka Nice!! I will use this option for now 😄

**Comment by sawka** [comment]
in the background presets, you can now set: `"bg:activebordercolor": "rgba(0, 0, 255, 1.0)"` to override the active border color for blocks
