### ISSUE TITLE
[Bug]: Invalid links in web browser block show a blank page instead of an error.

### ISSUE THREAD

**Issue by ShadowArcanist** [wavetermdev/waveterm#1023]
### Current Behavior

When visiting an invalid link in the web browser block, it displays a blank white page

Visiting a non existent link on the web browser block and you will get a white blank page ,  -- Example visit `https://test.waveterm.dev/` from the web browser block and it will show you a white blank page instead of showing a error.

![image](https://github.com/user-attachments/assets/e22eb446-f473-4b2b-8078-c6c3ffdd16ab)

### Expected Behavior

When visiting an invalid link, an error message should appear explaining why the link cannot be loaded.
![image](https://github.com/user-attachments/assets/9ba4295c-9669-429e-91ae-62a7439252ca)

### Steps To Reproduce

1. Open the Web browser block
2. Paste the url `https://test.waveterm.dev`on the url bar and hit enter key.

### Wave Version

0.8.11 (202410110234)

### OS

macOS Sonoma Version 14.7 (23H124)

### Architecture

arm64

### Anything else?

Running Wave with this configuration (settings.json)
```{
  "ai:baseurl": "http://127.0.0.1:11434/v1",
  "ai:model": "llama3.1:latest",
  "term:fontsize": 16,
  "term:fontfamily": "JetBrainsMono Nerd Font",
  "term:disablewebgl": false,
  "editor:minimapenabled": false,
  "editor:stickscrollenabled": true,
  "web:openlinksinternally": false,
  "web:defaulturl": "https://shadowarcanist.com",
  "web:defaultsearch": "https://duckduckgo.com/search?q={query}",
  "autoupdate:enabled": true,
  "autoupdate:channel": "latest",
  "widget:showhelp": false,
  "window:transparent": true, 
  "window:blur": false,         
  "window:opacity": 0.1,
  "window:bgcolor": "#000000",
  "window:reducedmotion": false,
  "window:tilegapsize": 4,
  "window:disablehardwareacceleration": false,
  "telemetry:enabled": false
}
```

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Good catch!
