### ISSUE TITLE
[Feature]: move settings under $HOME/.config/waveterm

### ISSUE THREAD

**Issue by maxadamo** [wavetermdev/waveterm#1025]
### Feature description

settings are currently stored under `$HOME/.waveterm`, and as a result of this the home directory is very cluttered. 

### Implementation Suggestion

The new applications tend to store the settings under `$HOME/.config/<app-name>`

**Comment by esimkowitz** [comment]
The location can be updated by manually moving the directory and setting the WAVETERM_HOME env var to the new location. Does this satisfy your use case? I'm hesitant to change the default right now as it might make the folder harder to find. Open to being convinced otherwise

**Comment by abhabongse** [comment]
I would like to chip in a bit. Most modern applications in *nix (Linux, MacOS, etc.) respect [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/), which means that:

- User configurations should normally be stored in `.config/waveterm/*`
- Other data (not intended to be user-configurable) should be stored in `.local/share/waveterm/*`

Using `$HOME/.waveterm` is a somewhat surprising behavior for modern users of *nix, which may go against the point that "it might make the folder harder to find," depending on each user's diversed background experience.

Personally, I'm defining `$WAVETERM_HOME` for now, and it's not a big deal at all. But moving towards a common convention would also be nice.

Sorry if I'm coming out as rude or too demanding.

**Comment by esimkowitz** [comment]
Y'all got me convinced 😄

Working to get this merged in v0.9, working out a back-compat story

**Comment by maxadamo** [comment]
Lots of changes have been implemented over time. 
Back in the days, the root directory (`/`) was the home directory for root user, and it was cluttered (and everyone could list the files on `/`), `/bin` became a symlink, and I guess it will vanish at some point, sticky bits on files have been removed as well... so, yeah: let's ask to change WAVETERM_HOME to those who prefer using the $HOME/.waveterm directory 😸 

Thanks.

**Comment by esimkowitz** [comment]
yeah definitely leaving it there for folks who prefer it, but the new default will be XDG

**Comment by esimkowitz** [comment]
@maxadamo @abhabongse I'm a bit hesitant to set .config as the default for macOS, given it's not the platform default (~/Library/Application Support). Do you have XDG_CONFIG_HOME, etc. manually set on macOS?

**Comment by esimkowitz** [comment]
I've updated the PR with what I feel is a good compromise.

Going forward for new installations, config and data files will be stored at the platform default paths, as defined by [env-paths](https://www.npmjs.com/package/env-paths).

For backwards compatibility, if the `~/.waveterm` or WAVETERM_HOME directory exists and contains valid data, it will be used. If this check fails, then WAVETERM_DATA_HOME and WAVETERM_CONFIG_HOME will be used. If these are not defined, then XDG_DATA_HOME and XDG_CONFIG_HOME will be used. Finally, if none of these are defined, the env-paths defaults will be used.

As with the existing app, dev instances will write to `waveterm-dev` directories, while all others will write to `waveterm`.

**Comment by maxadamo** [comment]
> I've updated the PR with what I feel is a good compromise.
> 
> Going forward for new installations, config and data files will be stored at the platform default paths, as defined by [env-paths](https://www.npmjs.com/package/env-paths).
> 
> For backwards compatibility, if the `~/.waveterm` or `WAVETERM_HOME` directory exists and contains valid data, it will be used. If this check fails, then `WAVETERM_DATA_HOME` and `WAVETERM_CONFIG_HOME` will be used. If these are not defined, then `XDG_DATA_HOME` and `XDG_CONFIG_HOME` will be used. Finally, if none of these are defined, the [env-paths](https://www.npmjs.com/package/env-paths) defaults will be used.
> 

I don't have the XDG variables on my Mac. The solution that you are implementing looks good to me. 
Some application installed with brew, store their configurations under $HOME/.config, some others don't. Maybe I should raise an issue for those applications, which are not adhering to the new standard. 
For instance, even in Linux, Google Chrome respects the XDG standard but Firefox doesn't.

**Comment by esimkowitz** [comment]
this is completed
