### ISSUE TITLE
[Bug]: Editor loses unsaved changes when switching tabs

### ISSUE THREAD

**Issue by ToontjeM** [wavetermdev/waveterm#1027]
### Current Behavior

Editor loses unsaved changes when switching tabs. 

### Expected Behavior

Editor retains unsaved changes. 

### Steps To Reproduce

Open two tabs. 
Edit a file in tab 1. Make changes, don’t save them. 
Switch to tab 2. 
Switch back to tab 1. 
Unsaved changes are gone. File is in its last saved state. 

### Wave Version

On my phone now, so cannot see. But latest as of today. 

### OS

Ubuntu 24.10

### Architecture

x64

### Anything else?

KDE Plasma 6.1

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Trying to track this down, do you know if this is a new regression? It may get resolved on its own as we're about to merge a pretty big change to our tab architecture to make it operate a bit more like browser tabs

**Comment by ToontjeM** [comment]
I have not seen this behaviour before, so I guess it’s from the last one or two versions.

**Comment by sawka** [comment]
this should be fixed on v0.9 as we preserve the tab states on tab switch
