### ISSUE TITLE
[Bug]: Window Transparency Not Working in Full-Screen Mode

### ISSUE THREAD

**Issue by ShadowArcanist** [wavetermdev/waveterm#1034]
### Current Behavior

When switching to full-screen mode in the Wave app, the transparency of the window is lost.

https://github.com/user-attachments/assets/6cf9afdc-fe87-4f11-84b5-58ed74ee4440

### Expected Behavior

The window should retain its transparency when entering full-screen mode.

### Steps To Reproduce

1. Modify the settings JSON file to include:
- `"window:opacity": 0`
- `"window:bgcolor": "#000000"`
2. Enter full-screen mode.

### Wave Version

 0.8.11 (202410110234)

### OS

Mac OS Sonoma 14.7 (23H124)

### Architecture

arm64

### Anything else?

This issue has only been tested on macOS.

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Ah, I believe this is a macOS limitation. The transparency is still there, but macOS doesn't carry your background over when you move to full screen, since full screen removes an app from the desktop. I don't think there's anything we can do about this unfortunately.

**Comment by ShadowArcanist** [comment]
Ahh Okay, @esimkowitz Thanks for checking!!
