### ISSUE TITLE
[Feature]: Code Line Wrapping in Editor/Preview Block

### ISSUE THREAD

**Issue by ShadowArcanist** [wavetermdev/waveterm#1038]
### Feature description

Right now, in the code editor/preview window, long lines of code do not wrap to the next line. Users have to scroll horizontally to see the whole line, which is frustrating. It would be much better if long lines could wrap based on the width of the block.

![image](https://github.com/user-attachments/assets/8ded7ee1-fb1c-4149-98a8-e428ccc7e473)

**Comment by sawka** [comment]
in v0.9.1
