### ISSUE TITLE
[Bug]:  v0.8.12-beta.0 - Move AI model configs to presets and add a dropdown to swap between configs

### ISSUE THREAD

**Issue by C0sm0cats** [wavetermdev/waveterm#1040]
### Current Behavior

Hello
When opening multiple AI windows, the labels in the title (e.g., "global Default") accumulate additional values (e.g., "gpt-4o-mini"). This seems to be related to the logic of recalculating the presetMap, which is executed each time the map is recalculated.

The function that modifies the display:name of presets is called every time the presetMap is recalculated, leading to additional labels in the title. The current conditions for determining the display:name do not appear to be strict enough, allowing values to accumulate.

cosmo
Manjaro user

### Expected Behavior

The titles of the AI windows should display only the relevant label (e.g., "global Default") without accumulating additional values (e.g., "gpt-4o-mini"). Each window should have a clear and distinct title that accurately reflects the current preset without duplicates or unnecessary additions.

### Steps To Reproduce

Launch an AI window (ensure the default preset is applied).
Note the title of the window (should be "global Default").
Open additional AI windows multiple times.
Observe the titles of the newly opened windows.

### Wave Version

v0.8.12-beta.0 

### OS

Manjaro

### Architecture

None

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Haha that's silly, will fix

**Comment by esimkowitz** [comment]
Fixed, will show up in next beta
