### ISSUE TITLE
[Bug]: Crash on Startup @ amd64-v0.8.12-beta.0.deb & amd-64-0.8.11.deb @ Ubuntu 24.04.1

### ISSUE THREAD

**Issue by xbais** [wavetermdev/waveterm#1049]
### Current Behavior

Application crashes on startup without showing any GUI with the following error:
```bash
[15654:1017/125238.273688:FATAL:credentials.cc(132)] Check failed: . : Permission denied (13)
Trace/breakpoint trap (core dumped)
```
Please see the logfile attached below:
[waveapp.log](https://github.com/user-attachments/files/17407758/waveapp.log)

### Expected Behavior

The application should start normally and display a stable GUI.

### Steps To Reproduce

1. On an Ubuntu 24.04.1 machine
2. Install any of the following DEB packages : amd64-v0.8.12-beta.0.deb & amd-64-0.8.11.deb (I used `sudo apt install ./mydeb.deb` format for installation)
3. Then open a terminal with bash, and type the command `waveterm` and hit enter.

### Wave Version

0.8.12-bet.0 and 0.8.11

### OS

Ubuntu 24.04.1

### Architecture

x64

### Questionnaire

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Are you running on a readonly filesystem? Looks like the app is running from a mount in the /tmp dir.. electronpath=/tmp/.mount_wavete3po1LP/resources/app.asar/dist gopath=/tmp/.mount_wavete3po1LP/resources/app.asar.unpacked/dist

**Comment by xbais** [comment]
No, its not a read only file system as far as I know. I ran it on my laptop, everything else is running fine. I installed other DEB packages (like VS Code) after installing Waveterm. They seem to be running fine.

**Comment by esimkowitz** [comment]
Can you try running `sudo apt remove waveterm` and then do it again?

**Comment by xbais** [comment]
Yes I did run the test. I uninstalled the waveterm application, then performed `sudo apt autoremove` (which did not remove any remnant files, and recovered NO disk space). Then I reinstalled the `beta` DEB package. At this point I will clarify that I am using ZSH. After installation, when I run the application from ZSH via `waveterm` command, it opens. I close the windows, and re-run it it opens again. Then I checked if it runs in BASH, so I typed `bash` to get into the bash terminal, then re-ran the `waveterm` command, and it gave the same error. Then I exited BASH, and rebooted my computer to see if the program atleast continues to run from ZSH. But on rebooting the system, it stopped working in ZSH as well and started throwing the same error:

```bash
[6045:1018/003353.101128:FATAL:credentials.cc(132)] Check failed: . : Permission denied (13)
[1]    6045 trace trap (core dumped)  waveterm
``` 

Here are the full logs...
[waveapp.log](https://github.com/user-attachments/files/17421333/waveapp.log)

I should warn you that I am also using the AppImage version of Waveterm, in case they both log in the same file, the logs can be difficult to understand...the later section of the logs must contain the errors from the ZSH and BASH runs.

**Comment by esimkowitz** [comment]
What update channel are you set to in ~/.waveterm/config/settings.json?

**Comment by esimkowitz** [comment]
Also are both versions of the app running at the same time? Because that would certainly cause problems

**Comment by esimkowitz** [comment]
The AppImage version might explain the /tmp directory...

**Comment by xbais** [comment]
Hey, 
- Whether the Appimage is able to run alongside the DEB application or not I will let you know in a while when I check on my other laptop where both run. 
- On my present laptop where the DEB application is crashing, I checked again, and the DEB app crashes irrespective of the Appimage, meaning even if the Appimage is not already running the DEB will crash on startup.

**Comment by xbais** [comment]
I also checked whether the AppImage is able to work alongside the installed DEB package...
No, it is unable to. Only one of them works at a time. The other refuses to run when one of them is already running.

**Comment by esimkowitz** [comment]
Hey @xbais checking, are you still seeing an issue on 0.8.12?

**Comment by xbais** [comment]
> Hey @xbais checking, are you still seeing an issue on 0.8.12?

Yes this issue persists in the application installed via v0.8.12 DEB package on Ubuntu 24.04.1.

**Comment by esimkowitz** [comment]
For those seeing this issue, try https://github.com/wavetermdev/waveterm/issues/1147#issuecomment-2468827130

**Comment by xbais** [comment]
( Comment permalink = https://github.com/wavetermdev/waveterm/issues/1147#issuecomment-2468827130 )

**Comment by esimkowitz** [comment]
@xbais can you confirm if the linked suggestion fixed the issue for you?

**Comment by xbais** [comment]
Yes will let you know by today...

**Comment by xbais** [comment]
@esimkowitz , I checked if running the command in [#1147 (comment)](https://github.com/wavetermdev/waveterm/issues/1147#issuecomment-2468827130) solves the issue or not. It seems to have only solved the issue PARTIALLY. 

So, here is what happens:
1. I perform a fresh install of the latest 0.9.2 x64 DEB file on Ubuntu 24.04 LTS
2. I run the app, via `waveterm` command on the terminal. It runs this first time.
3. I reboot my system and repeat step (2), it doesn't run and returns the permission denied error stated in this issue.
4. I run the command in [#1147 (comment)](https://github.com/wavetermdev/waveterm/issues/1147#issuecomment-2468827130)  without rebooting the system,  then run waveterm again. IT RUNS !
5. I reboot the system, and run waveterm again, it returns the error again.

Now, I will have to repeat step (4) every time I reboot to make waveterm work in that session. Meaning the command in [#1147 (comment)](https://github.com/wavetermdev/waveterm/issues/1147#issuecomment-2468827130) will have to be run after every reboot.

**Adding the command as a shell command which runs every time on system reboot could temporarily solve the issue.**

**Comment by esimkowitz** [comment]
Do you have an NVIDIA graphics driver?

**Comment by xbais** [comment]
> Do you have an NVIDIA graphics driver?

Yes I checked on two different systems. One has NVIDIA graphics card with NVIDIA driver, other doesn't. And this problem seems to be happening in the system with NVIDIA graphics card and drivers.

**Comment by esimkowitz** [comment]
I don't believe this is a bug with Wave Terminal, rather a generic incompatibility with your driver settings and Electron/Chromium. I'm not a Linux expert so take my advice with a grain of salt and definitely double check with your own sources, but if the `sysctl` setting I mentioned resolves the error, that seems to me like a reasonable resolution. 

`sysctl` commands don't persist after reboot, but you can make that command into a persisted config as described here: https://serverfault.com/questions/954499/sysctl-not-sticking-after-reboot

**Comment by xbais** [comment]
Okay cool then, I will close this bug for now. People may re-open it if the face the same issue or it surfaces that the bug might be originating from Waveterm...

**Comment by esimkowitz** [comment]
You may also want to consult this wiki, it goes over some more advanced tweaks you can make to your global Chromium conf files to fix driver compatibility. These are beyond the scope of this project for now as we don't have the capacity to validate optimizations on a wide range of Linux configurations, but if you find any that seem general enough feel free to open them as feature requests!
