### ISSUE TITLE
[Bug]: term:theme option does not change theme properly

### ISSUE THREAD

**Issue by Pribess** [wavetermdev/waveterm#1066]
### Current Behavior

https://github.com/user-attachments/assets/67a52868-498a-4949-8966-16e29d59b54e

https://github.com/user-attachments/assets/b5da339a-3272-427f-90be-094a0a00add2

It seems to change only the color of background

### Expected Behavior

All feature of the theme should be applied properly

### Steps To Reproduce

set "term:theme" option

### Wave Version

v0.8.11

### OS

macOS 14.6.1

### Architecture

x64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [X] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
It looks right to me, what part of it isn't applying the way you'd expect?

**Comment by sawka** [comment]
thanks for reporting.  i just reproduced it on my machine.  you're right, it is not applying the default theme correctly on update (only after a refresh).

**Comment by sawka** [comment]
fixed in v0.9.1
