### ISSUE TITLE
Unable to display filename with Chinese Characters

### ISSUE THREAD

**Issue by wyatt-wong** [wavetermdev/waveterm#108]
I have a bunch of PDF file in with Chinese characters in the filename, and when I issue "ls" command, I see all Chinese characters becomes ????

So I wonder does Wave Terminal Supports Unicode and UTF-8 ?

<img width="965" alt="Screenshot 2023-11-30 at 12 29 56 AM" src="https://github.com/wavetermdev/waveterm/assets/10095648/4ee3bbe7-52fa-416e-a6db-03220d939c78">

**Comment by sawka** [comment]
Closing as a duplicate to consolidate the international character issue in the terminal into this issue: https://github.com/wavetermdev/waveterm/issues/88
