### ISSUE TITLE
Ctrl + S File Editor Keybinding Not Working in Ubuntu 24.04.1

### ISSUE THREAD

**Issue by xbais** [wavetermdev/waveterm#1081]
### Current Behavior

When opening a file in the text editor, after editing Ctrl + S cannot be used to save the file. The user has to manually click on the Save button.

### Expected Behavior

Pressing Ctrl + S should save the file.

### Steps To Reproduce

1. On an Ubuntu 24.04.1 system (64 bit)
2. Install [amd-64 v0.8.12 (DEB)](https://objects.githubusercontent.com/github-production-release-asset-2e65be/501045649/3f688e64-cc4e-4abe-83c2-2fe63f8bf09a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241020%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241020T013307Z&X-Amz-Expires=300&X-Amz-Signature=07ec3114f4309659460fe3be4f26f3c82bc011351a9153a065af66b89ca70d55&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dwaveterm-linux-amd64-0.8.12.deb&response-content-type=application%2Foctet-stream) or x86_64 [AppImage](https://objects.githubusercontent.com/github-production-release-asset-2e65be/501045649/28e17b22-4026-48d7-81c3-05cf4c7045f7?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241020%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241020T013307Z&X-Amz-Expires=300&X-Amz-Signature=3fb0b46beb9856caa5cd894dcef25e50667b35443b57710d5678b9c8b4bb89d3&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dwaveterm-linux-x86_64-0.8.12.AppImage&response-content-type=application%2Foctet-stream)
3. Open waveterm.
4. If waveterm GUI opens, open the file editor in waveterm, try to edit a text file,
5. Try saving it by pressing Ctrl + S
6. Even after pressing Ctrl + S, the save button remains bright green (doesn't get disabled) and the file stays unsaved 

### Wave Version

v0.8.12

### OS

Ubuntu 24.04.1

### Architecture

x64

### Questionnaire

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by sawka** [comment]
Right now the keybinding for save is Alt+S on windows/linux.  We discussed internally and agree that in the preview editor on Windows/Linux Ctrl+S should also be supported.

**Comment by sawka** [comment]
shipped in v0.9.1
