### ISSUE TITLE
[Bug]: Linux Appimage Requires --no-sandbox Flag To Run

### ISSUE THREAD

**Issue by xbais** [wavetermdev/waveterm#1082]
### Current Behavior

I am reporting this issue just so that the maintainers are aware of this behaviour of the application. The AppImage version of the release doesn't run directly. It only runs when the user runs it from terminal and provides the `--no-sandbox` flag. When run without the flag, it simply terminates with the following error:
```bash
[10011:1020/073823.806701:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_wavetex5UeT9/chrome-sandbox is owned by root and has mode 4755.
[1]    10011 trace trap (core dumped)  ./waveterm-linux-x86_64-0.8.12.AppImage
```

## Suggestions
1. If this is a bug, then the authors can fix it when they get time
2. If it is an expected behaviour, then maybe it would be nice to add this to installation steps (or steps to run) in https://github.com/wavetermdev/waveterm/edit/main/README.md so that the layman doesn't get confused and beat his head :laughing: 

### Expected Behavior

Not sure of the expected behaviour since the app is a terminal emulator I don't expect it to not require full system access (ie. running outside a sandboxed environment), but most other AppImages work directly after installing Fuse on the system and making the AppImage executable...meaning they don't require the flag.

### Steps To Reproduce

1. On a machine with Ubuntu 24.04.1
2. Download [waveterm-linux-x86_64-0.8.12.AppImage](https://github.com/wavetermdev/waveterm/releases/download/v0.8.12/waveterm-linux-arm64-0.8.12.AppImage), make it executable
3. Install Fuse if not already installed (`sudo apt install fuse`)
4. In a terminal, cd to the folder where the file is downloaded
5. Run the following command in terminal : `./waveterm-linux-x86_64-0.8.12.AppImage`

This will give the sandbox error. Next run the following command with the flag : `./waveterm-linux-x86_64-0.8.12.AppImage -no-sandbox`. This will probably work and the app should open.

### Wave Version

v0.8.12

### OS

Ubuntu 24.04.1

### Architecture

x64

### Questionnaire

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Definitely a bug, will look further

**Comment by esimkowitz** [comment]
@xbais I'm having trouble reproducing this. How do you run AppImages on your machine? Are you using AppImageLauncher?

**Comment by xbais** [comment]
Hi !
I run it in one of these two ways:
1. Make the appimage executable, run by double clicking on it in file manager.
2. If the above fails, run it from terminal to see any logged errors.

**Comment by esimkowitz** [comment]
@xbais can you try downloading the ubuntu-latest artifact from this workflow run and try running the AppImage inside it? Hopefully this resolves the sandbox issue: https://github.com/wavetermdev/waveterm/actions/runs/11447869858

**Comment by esimkowitz** [comment]
Hmm okay I was able to repro on my machine and unfortunately my fixes don't work for appimage. 

https://github.com/electron-userland/electron-builder/issues/4495

It seems like no one in the Electron world cares to really fix this as they've all moved on to Snap and Flatpak. Given AppImage is barely supported anymore, I think the best course of action is to abandon it and follow everyone else to Snap and Flatpak. I'll look into getting these targets added. Sorry for the unsatisfying conclusion

**Comment by xbais** [comment]
No issues.. cool that the project moved ahead on this part...whatever the decided course of action is... :+1:
