### ISSUE TITLE
[Bug]: Link to telemetry documentation in welcome splash dialog is broken

### ISSUE THREAD

**Issue by NorthernScott** [wavetermdev/waveterm#1085]
### Current Behavior

The link to the telemetry data on the welcome splash dialog points to <https://docs.waveterm.dev/reference/telemetry>. The user sees a 404 error page.

![image](https://github.com/user-attachments/assets/bc2dd5bc-f8b8-41a5-83a7-f6038ed3d8f9)

### Expected Behavior

The link should point to <https://docs.waveterm.dev/telemetry>, which appears to be the correct link.

### Steps To Reproduce

1. Using Windows, installed with MSI (Wave-win32-x64-0.8.12.msi).
2. On first startup of the program, the splash dialog is shown.
3. Click on the *telemetry data* link under the **Telemetry** bullet.

### Wave Version

v0.8.12

### OS

Windows 11

### Architecture

x64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
good catch, fixed

**Comment by NorthernScott** [comment]
Thanks.
