### ISSUE TITLE
[Bug]: Doesn't trigger microphone permission on macOS

### ISSUE THREAD

**Issue by CallMeLaNN** [wavetermdev/waveterm#1086]
### Current Behavior

I was running `pyaudio` to record voice but it doesn't work and .wav produced have empty bytes. I thought my installation or pyaudio issue but now I realize the terminal issue. I can record audio with default Terminal app.

Latest Wave app doesn't trigger microphone permission just like Terminal when using `pyaudio.open(input=True,...)`.

Instead of I give a pyaudio script, you can try `sox`.

### Expected Behavior

Prompt the mic permission and have audio stream recorded

### Steps To Reproduce

1. `brew install sox`
2. `sox -d -t wav - | play -`
3. Increase your volume
4. Say something

After step 2, you should be prompted for the mic permission.
The you should hear yourself as you say with some echo for speaker.

Note: Use `tccutil reset Microphone` to let apps to ask for the permission again.

### Wave Version

0.8.12

### OS

macOS 12.6

### Architecture

arm64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [X] I don't have time to fix this right now, but maybe later

**Comment by sawka** [comment]
Interesting.  Thanks for reporting this.  I haven't tried recording audio (or using the microphone) in Wave yet so we haven't run across this.  It should be possible, like you said, to get that permission from the OS.  Once we have a test case to work on we should be able to figure it out.

**Comment by sawka** [comment]
ah, my latest attempt worked!  thanks for the instructions on how to test this.  this should make the v0.9.1 build.
<img width="430" alt="Screenshot 2024-11-01 at 1 04 31 PM" src="https://github.com/user-attachments/assets/0602dd92-bcc3-4dfa-80ee-62ebb6dba55d">

**Comment by CallMeLaNN** [comment]
You are welcome. That's the least I can contribute to. Hope I can catchup with the 0.8 and 0.9 releases. I missed the 0.7 UI but 0.8 more productive and it wasn't auto update IIRC, so I'll watch here.

**Comment by esimkowitz** [comment]
Hey @CallMeLaNN is this still an issue for you?

**Comment by CallMeLaNN** [comment]
@esimkowitz  Yup, its working. Mac ask for mic and I can hear myself.
Maybe I have to close this. Thanks 🚀
