### ISSUE TITLE
Invalid cwd for command

### ISSUE THREAD

**Issue by nobodywasishere** [wavetermdev/waveterm#112]
**Describe the bug**
When attempting to execute any command, it returns an error: `invalid cwd ' /home/margret ' for command: stat /home/margret : no such file or directory`. Running `stat /home/margret` from a different terminal works. Version v0.5.0.

**To Reproduce**
1. Download application
2. Click on terminal box and type any command, press enter

**Expected behavior**
The command should execute and the results should be returned.

**Screenshots**

![image](https://github.com/wavetermdev/waveterm/assets/32797552/5d8c7003-140e-4340-82b4-2b4caa4f1035)

**Desktop (please complete the following information):**
 - OS: EndeavourOS (Arch Linux) X86_64 [e.g. MacOS/Linux, x64 or arm64]
 - Version: v0.5.0

```
$ neofetch 

                     ./o.                  margret@nobody-t14 
                   ./sssso-                ------------------ 
                 `:osssssss+-              OS: EndeavourOS Linux x86_64 
               `:+sssssssssso/.            Host: 20UES3GB00 ThinkPad T14 Gen 1 
             `-/ossssssssssssso/.          Kernel: 6.6.3-arch1-1 
           `-/+sssssssssssssssso+:`        Uptime: 35 mins 
         `-:/+sssssssssssssssssso+/.       Packages: 2085 (pacman) 
       `.://osssssssssssssssssssso++-      Shell: bash 5.2.21 
      .://+ssssssssssssssssssssssso++:     Resolution: 1920x1080 
    .:///ossssssssssssssssssssssssso++:    DE: Plasma 5.27.9 
  `:////ssssssssssssssssssssssssssso+++.   WM: KWin 
`-////+ssssssssssssssssssssssssssso++++-   Theme: [Plasma], Breeze [GTK2/3] 
 `..-+oosssssssssssssssssssssssso+++++/`   Icons: [Plasma], breeze-dark [GTK2/3] 
   ./++++++++++++++++++++++++++++++/:.     Terminal: yakuake 
  `:::::::::::::::::::::::::------``       CPU: AMD Ryzen 5 PRO 4650U with Radeon Graphics (12) @ 2.100GHz 
                                           GPU: AMD ATI 07:00.0 Renoir 
                                           Memory: 5564MiB / 15212MiB 

```

**Comment by sawka** [comment]
if you want to just conditionally remove that line for Wave, you can test the $WAVESHELL variable:

```
if [ -z "$WAVESHELL" ]; then
    trap echo DEBUG
fi
```

we set both $WAVESHELL (to be the binary of the waveshell/mshell executable), and set $WAVESHELL_VERSION as well.

**Comment by nobodywasishere** [comment]
Thank you!
