### ISSUE TITLE
[Bug]: v0.9.0 - Application freezes and crashes when clicking on "View" from the main menu

### ISSUE THREAD

**Issue by C0sm0cats** [wavetermdev/waveterm#1152]
### Current Behavior

I am experiencing an issue with the application on Manjaro. When I click on the main menu and select "View," The "View" submenu don't open , the application freezes and then closes unexpectedly.

### Expected Behavior

The "View" submenu should open without any issues.

### Steps To Reproduce

    Open the application.
    Click on the main menu.
    Select "View."

### Wave Version

v0.9.0

### OS

Manjaro

### Architecture

x64

**Comment by UnJavaScripter** [comment]
Pus one here: 

### Current Behavior

Wave closes immediately after attempting to open the "View" sub-menu

### Steps To Reproduce

```
Triggering an event that will open the "View" sub-menu:
- Clicking
- Hovering over
- Navigating using the keyboard
```

*Message from a terminal that invoked it*

```
Trace/breakpoint trap (core dumped)
```

### Wave Version
v0.9.0

### OS
Pop!_OS

### Architecture
x64

#### Additional details:

- Display Manager: gdm3

**Comment by esimkowitz** [comment]
Can repro, testing a fix

**Comment by esimkowitz** [comment]
See linked PR, I think this is an Electron bug...
