### ISSUE TITLE
[Bug]: v0.9.0 - Tabs getting deleted after auto update

### ISSUE THREAD

**Issue by C0sm0cats** [wavetermdev/waveterm#1167]
### Current Behavior

I've noticed that every time I open and close the application, the tab in my browser is renamed by incrementing T number . Additionally, if I open multiple tabs, upon reopening the application, it only restores one tab and increments the number on the title. the application does not save its state, resulting in a loss of unsaved progress.
![image](https://github.com/user-attachments/assets/24b9a3a9-c869-4f85-995f-6feca89eb28f)

### Expected Behavior

The tab title should remain consistent each time the application is opened and closed, without any incremental numbering.

### Steps To Reproduce

Open the application.
Open a new tab or several tabs
Close the application.
Reopen the application.
Observe the tab title.

### Wave Version

v0.9.0

### Platform

Linux

### OS Version/Distribution

manjaro

### Architecture

x64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Exc4l1buR** [comment]
I'm experiencing the same thing Tuxedo OS (based on Ubuntu).
Though it does seem to keep the state if you crash it by trying to open the view menu from the main menu.

**Comment by crush2000** [comment]
I have the same issue on ZorinOS 17.2 (based on Ubuntu)

**Comment by C0sm0cats** [comment]
yes and i guess you have this bug also => https://github.com/wavetermdev/waveterm/issues/1152

**Comment by Exc4l1buR** [comment]
yup, also i dont know if this is relevent but im using wayland on my system

**Comment by crush2000** [comment]
Rollback to 0.8.12 didn't work for me. First run on default set of widgets is ok but form second and next it's broken like in 0.9.0. Snap also is broken.

**Comment by esimkowitz** [comment]
We believe that this was a race condition between our updater and our window manager. During normal use, if you close a window we delete it from the backend, including all the tabs (with the exception of the last tab). This should not happen during an update, though, as we set a flag before shutdown to bypass this step. We believe that with our refactor of our window manager for 0.9, the timing for the event that triggers the window close changed and the event was firing before the status flag was set by the updater. This should now be fixed as we added a delay after setting this flag before we actually trigger the install.

Going forward, this will be fixed more robustly by us reintroducing workspace support and adding automatic archiving of old windows. We were hopeful workspaces would make it into this last release, but it needs some more polishing.

**Comment by esimkowitz** [comment]
It may happen again with the next update, but after that it should not happen again.

**Comment by C0sm0cats** [comment]
FYI, the tab keeps renamed by incrementing T number on fresh install with Version 0.9.1-beta.2

**Comment by sawka** [comment]
The incrementing "T" numbers is a feature (I added) which names the tabs using a *global* counter (I thought it was fun to see the total number of tabs i've created in the lifetime of the app).  Otherwise you get the same "T1", "T2", "T3" when you open tabs.  Didn't realize that this was so disruptive.  I can change the logic back to the old numbering scheme and maybe just create an internal stats table for things like this.

Ah, I see though with the T16 -> T17 issue.  So when you close the last tab it does actually destroy that tab (which then closes the app).  When we restart, we always ensure there is at least one tab.  Since there were no tabs left after the last shutdown, we need to create a new one... with the global counter that is now T17.

**Comment by sawka** [comment]
One more note.  If you want to retain the tabs/windows, you need to use the App->Quit functionality.  That should make sure no tabs/windows get destroyed on shutdown so when you start it back up they all get restored (no new tabs should get created)

**Comment by C0sm0cats** [comment]
Hi @sawka,

I understand the fun idea behind the incrementing "T" global counter, but it does seem a bit disruptive, Your suggestion to revert to the old numbering scheme while keeping an internal stats table sounds like a solid compromise.

Maybe you could also consider adding an option in the settings to choose between the two naming conventions? This way, users can pick what works best for them.  

And i hadn’t even noticed that we could also rename it!

It might be a good idea to handle closing the last tab differently to avoid this situation. Maybe allowing the app to stay open even when the last tab is closed would help?

about retaining the tabs/windows, the close button on the window produces the same effect, ensuring that the tabs/windows are retained when the app is closed.

WR

**Comment by sawka** [comment]
I think this issue has been fixed in the v0.9.1 release, but will hold off on closing it until we get some confirmation

**Comment by C0sm0cats** [comment]
yes, I agree, and the latest version has addressed the issue with multiple tabs. However, for closing the last tab, a confirmation prompt before quitting the application could be beneficial. This might give users the chance to reconsider their decision and help prevent accidental closures.

**Comment by esimkowitz** [comment]
Closing this as resolved
