### ISSUE TITLE
[Bug]: Unable to view/edit AWK (.awk) files via the built-in code editor

### ISSUE THREAD

**Issue by jpotter23** [wavetermdev/waveterm#1175]
### Current Behavior

You can see below that I opened the awk file in question in the bottom pain via: `wsh view assert.awk` and got the message: `Preview (application/x-awk)` instead of seeing the code. I then also printed the file in the shell pane via `cat assert.awk` to illustrate that there is indeed AWK code in the file. I tried this on multiple .awk files in multiple locations, with and without spaces or other characters that need to be properly escaped in their path. All produced the same result. So my test from the screenshot below was as simple as possible, using an .awk file in the current working directory:

![image](https://github.com/user-attachments/assets/97aedd64-eaa5-4d0e-a461-21e0572602df)

### Expected Behavior

We should get a syntax-highlighted, editable copy of the code in the said .awk file. 
We should be able to read and edit the code as with other file types. 

### Steps To Reproduce

1. Open an awk file in the editor via: `wsh edit myawkfile.awk` 
2. Notice that you see only the message: `Preview (application/x-awk)` 
    * No code is displayed.
    * No syntax highlighting

### Wave Version

v0.9.0

### Platform

Windows

### OS Version/Distribution

Windows 11 - v: 22H2 - b: 22621.4317

### Architecture

x64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by sawka** [comment]
thanks for reporting, those should definitely be editable.  will be fixed in the next release

**Comment by sawka** [comment]
fixed in v0.9.1
