### ISSUE TITLE
Anyway to delete or re-edit connections?

### ISSUE THREAD

**Issue by Mooling0602** [wavetermdev/waveterm#118]
**Describe the bug**
I found no way to delete or re-edit any one of existing connections. That's terrible but seems even no one mentioned, as I searched in the Internet.

**To Reproduce**
1. Open Waveterm Terminal;
2. Click on 'Connections';
3. Select a connection;
4. Failed to change user@host, and can't delete it.

**Desktop:**
 - OS: Linux, x64
 - Version: v0.5.0

**Comment by tracymiranda** [comment]
To delete a connection go to the connection, and click on "edit connection settings". Then you can click "Archive Connection". This will delete all of the connection information (key, password, alias, etc.) and remove it from the connection list. You can't modify an existing connection's user, host, or port. so once you archive it, you can recreate it with the right settings. 

This will be improved in the upcoming version so it is easier to do.

**Comment by sawka** [comment]
Updated in v0.5.1.  Now, when you open a connection, the delete button is at the top of the modal window.
