### ISSUE TITLE
[Bug]: Terminal does not resize when app maximize on 49-inch screen

### ISSUE THREAD

**Issue by C0sm0cats** [wavetermdev/waveterm#1195]
### Current Behavior

When I open the application on a 49-inch screen and maximize the window in maximize mode , the first terminal does not resize to fit the screen size. This results in suboptimal display and makes using the application less enjoyable.

app with one terminal
![image](https://github.com/user-attachments/assets/680a1758-df0f-4500-b0dc-d3a32c90a195)

resizing maximize with one terminal
![image](https://github.com/user-attachments/assets/4c1e369b-36ca-4cb4-8812-07e9de6451e7)

minimize (right side panel disappear)
![image](https://github.com/user-attachments/assets/6bf4ee3a-dd9f-4d94-af13-64734cee6802)

maximize opening second tab
![image](https://github.com/user-attachments/assets/ecee437e-3162-452f-9ff4-86a4a6a89a33)

minimize (right side panel disappear)
![image](https://github.com/user-attachments/assets/17ad7659-855e-494f-b87f-348807b3f23a)

### Expected Behavior

The first terminal should automatically resize to fit the maximized window.

### Steps To Reproduce

Open the application on a 49-inch screen.
Maximize the application window.
Observe that the first terminal does not adjust to the screen size.

### Wave Version

v0.9.1

### Platform

Linux

### OS Version/Distribution

manjaro

### Architecture

x64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Exc4l1buR** [comment]
got the same behavior on a 24" monitor

wave version: v0.9.1 (202411012241)
platform: linux
os/distro: tuxedo os
architecture: x64

**Comment by mbeware** [comment]
Same issue here.
This occurs when Pop!OS is in tilling mode, and I close an other application, or if I move wave from a small monitor to a large one.  In both those case, It's not the user (me) resizing, but the DE. 

It seem that wave  doesn't catch the notification for auto-resize. 

Client Version 0.9.1 (202411012241)
Update Channel: latest

OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.9.3-76060903-generic 
Uptime: 2 days, 5 hours, 23 mins 
Packages: 3087 (dpkg), 59 (flatpak) 
Shell: bash 5.1.16 
Resolution: 1920x1080, 1920x1080, 1920x1080 
DE: Unity 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: waveterm 
CPU: AMD Ryzen 5 5600G with Radeon Graphics (12) @ 3.900GHz 
GPU: AMD ATI 0c:00.0 Cezanne 
GPU: NVIDIA GeForce RTX 2060 Rev. A 
Memory: 38758MiB / 95919MiB

**Comment by coder-xander** [comment]
same issure on ubuntu 22.04.4 LTS desktop

**Comment by esimkowitz** [comment]
This should be fixed in 0.9.2. There's still a bit of a delay with the resizing when in fullscreen mode, looking into that
