### ISSUE TITLE
[Bug]: Crash when clicking on "View" in the 3dots menu

### ISSUE THREAD

**Issue by OracleToes** [wavetermdev/waveterm#1199]
### Current Behavior

The application is crashing as soon as I go to the "View" tab in the 3dots menu at the top. here is the error it produces:
```$ waveterm 
[3285855:1103/105610.973964:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[3285855:1103/105610.974014:ERROR:select_file_dialog_linux_portal.cc(294)] Failed to read portal version property
error configuring updater Error: ENOENT: no such file or directory, open '/usr/lib/electron33/resources/app-update.yml'
Trace/breakpoint trap (core dumped)
```

### Expected Behavior

I don't expect it to crash

### Steps To Reproduce

launch waveterm from xfce4-terminal, navigate the mouse to the 3dots menu at the top, click on the view tab, application crashes.

### Wave Version

4.4.1 (202411031049)

### Platform

Linux

### OS Version/Distribution

EndeavourOS

### Architecture

x64

### Questionnaire

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Not sure where you got the version string from, our latest version is 0.9.1 and this bug should be fixed there
