### ISSUE TITLE
connections with auth type key+password can not connect

### ISSUE THREAD

**Issue by lbwstco** [wavetermdev/waveterm#128]
**Describe the bug**
Connections with auth type key+password doesn't enter passphrase to connect, then cursor is flashing when the step is "Enter passphrase for key", after that it shows "connect timeout". 
My key  passphrase just contains letters and numbers.

**To Reproduce**
1. Go to 'Connections'
2. Click on '+ New Connection'
3. Config the server info and Click 'connect'

**Expected behavior**
Just connect to the server.

**Screenshots**
![Xnip2023-12-07_14-15-06](https://github.com/wavetermdev/waveterm/assets/6779378/4cf76854-9eaa-4ea8-8814-e4eb2b12680c)

**Desktop (please complete the following information):**
 - OS: MacOS 13.6
 - Version v0.5.1

**Additional context**
 -

**Comment by sawka** [comment]
Thanks for submitting.  This definitely looks like a bug.  I think at some point we changed the logic for how the passwords are handled and never retested the passcode case.

Assuming I can repo it (it looks really straightforward), will target to fix for the next release.

**Comment by oneirocosm** [comment]
Closing this as it should be fixed by #130
