### ISSUE TITLE
Waveterm should respect user's login shell (or at least $PATH) (Mac specific)

### ISSUE THREAD

**Issue by b2sc** [wavetermdev/waveterm#132]
**Describe the bug**
Waveterm always start `/bin/bash` as its base shell (see `electron/emain.ts`). If there is a different `bash`on the system, e.g. in `/opt/homebrew/bin/bash`, it is ignored. Also, the `$PATH` is ignored.

**To Reproduce**
1. Change user's login shell to `/opt/homebrew/bin/bash`
2. Start Waveterm
3. `echo $BASH_VERSION`
4. Version 3 bash is used.

**Expected behavior**
Waveterm should either
1. Use `dscl . -read /Users/$USER UserShell` to determine the user's login shell, and start that.
2. Find `bash` by looking at `$PATH`

**Screenshots**
-

**Desktop**
 - MacOS
 - Version v0.5.1

**Additional context**
-

**Comment by sawka** [comment]
you're 100% right.  obviously an oversight and will try to fix this ASAP.  using bash v4 or v5 is actually better for Wave as well.  thanks for submitting.

**Comment by berkeleynerd** [comment]
> you're 100% right. obviously an oversight and will try to fix this ASAP. using bash v4 or v5 is actually better for Wave as well. thanks for submitting.

It would be interesting to understand what we give up by not using bash over zsh.

**Comment by sawka** [comment]
> > you're 100% right. obviously an oversight and will try to fix this ASAP. using bash v4 or v5 is actually better for Wave as well. thanks for submitting.
> 
> It would be interesting to understand what we give up by not using bash over zsh.

We plan on supporting zsh in the future.  Currently the issue around using zsh is our syntax parser (which power command completion and substitutions) is bash syntax specific.  Also the code that reads/restores the environment is bash specific.  We need to make modifications to support zsh's variable/function syntax.
