### ISSUE TITLE
Specify OpenAI API Base url

### ISSUE THREAD

**Issue by shuther** [wavetermdev/waveterm#133]
**Is your feature request related to a problem? Please describe.**
I would like to use self hosted model or to leverage Azure endpoint.

**Describe the solution you'd like**
Be able to specify the openAI base url.

**Comment by sawka** [comment]
Thanks for your submission!  This makes a lot of sense and should be straightforward to implement.

**Comment by sawka** [comment]
For our own reference, linking to the docs for how to provide the config for setting the baseurl for the package we're using:
https://pkg.go.dev/github.com/sashabaranov/go-openai#ClientConfig
