### ISSUE TITLE
[Feature]: Please add hyperlink support for terminal blocks

### ISSUE THREAD

**Issue by plastikfan** [wavetermdev/waveterm#1357]
### Feature description

I am migrating from Warp and have noticed a missing feature in Wave. Seeing the output of a test run which may contain a stack trace, I have become accustomed to being able to cmd-click a source code reference and have that open up in my ide.

In the snapshot shown, using Warp, I would be able to cmd-click any source code reference, eg:

> /Users/plastikfan/dev/github/snivilised/pants/worker-pool-func-manifold_test.go:155
> /Users/plastikfan/dev/github/snivilised/pants/worker-pool-func-manifold.go:108
> /Users/plastikfan/dev/github/snivilised/pants/worker-pool-func-manifold.go:116

etc...

The same goes for web links that may appear in console output, they should also be cmd-clickable in a simlar fashion.

### Anything else?

<img width="1294" alt="WAVE-missing-hyperlinks" src="https://github.com/user-attachments/assets/f858f8fe-e104-403e-9439-ccccb88f1b7f">

**Comment by esimkowitz** [comment]
Fyi this was a bug, there was a regression in v0.8.11. The linked PR should fix this. There's still some improvements we could make like linking file paths to a preview widget, but that'll be a future enhancement
