### ISSUE TITLE
[Feature]: Allow for default command line application

### ISSUE THREAD

**Issue by Lizardbutt** [wavetermdev/waveterm#1434]
### Feature description

It would be nice to have the ability to set which command line application launches when opening a new terminal.

On windows, Windows Command Prompt, PowerShell 5, PowerShell 7, WSL, Python, etc

Linux, vim, nvim, etc

### Implementation Suggestion

Some kind of default settings, either via wsh editconfig or otherwise.

PowerShell 7 also does not support the wsh editconfig command - I know there's still users out there that use PS5 (weirdos) but I think lately PS7 has been the new "standard"

### Anything else?

I'll get another feature added for PS7 support.

**Comment by esimkowitz** [comment]
Same as #1435, check out https://docs.waveterm.dev/faq#on-windows-how-can-i-use-git-bash-as-my-default-shell

**Comment by esimkowitz** [comment]
You can also create custom widgets which you can assign to each of these commands: https://docs.waveterm.dev/customwidgets
