### ISSUE TITLE
impossible to connect to ubuntu with ssh setup to use password+totp

### ISSUE THREAD

**Issue by shuther** [wavetermdev/waveterm#145]
**Describe the bug**
tried with manual or password; either I am not requested to enter the validation key (manual mode keeps asking me for the password) either it hangs when I should type the validation key.

**To Reproduce**
1. setup TOTP using google approach
2. create new connection
3. Edit connection doesn't work

**Expected behavior**
connection should start.

**Desktop (please complete the following information):**
 - OS: M1
 - Version v0.5.1 through brew

**Comment by esimkowitz** [comment]
Could you provide a link or a more in-depth description of how you've configured your TOTP?

**Comment by sawka** [comment]
thanks for submitting!  we have some changes planned for how Wave deals with connections that require a password and keys that require passphrases.  this is also a good case to consider.  once we get a test case set up for this internally we'll try to get this working.

**Comment by oneirocosm** [comment]
This should theoretically be handled by the new ssh updates we're testing now, but I will need to actually test it before confirming that it's been fixed.

**Comment by sawka** [comment]
will close as the KbdInteractiveAuth is implemented.  can reopen if there is a specific problem with Google Authenticator.
