### ISSUE TITLE
[Bug]: Giscus Script in Waveterm Causes Page Redirect Instead of Loading iFrame

### ISSUE THREAD

**Issue by hahwul** [wavetermdev/waveterm#1487]
### Current Behavior

[Giscus](http://giscus.app) script in Waveterm leads to page redirect instead of iFrame generation.

### Expected Behavior

Giscus script should load within an iFrame in Waveterm without redirecting the page.

### Steps To Reproduce

1. Navigate to https://www.hahwul.com/2024/11/03/passivescan-in-owasp-noir/ 
2. Scroll down
3. When you encounter the Giscus code, it will cause Waveterm to redirect to src link instead of loading the iframe.

https://github.com/user-attachments/assets/f4d9f4bb-67e1-4515-9a7b-19dd92fda93c

As a result of my test, the same problem occurs on all pages that use comments with giscus. This shows a different way of working from general web browsers (firefox, safari, etc.).

### Wave Version

v0.9.3

### Platform

macOS

### OS Version/Distribution

macOS 15.1.1 (Sequoia)

### Architecture

arm64

### Questionnaire

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [X] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Oh interesting, yep definitely repros for me. I have an idea why this is happening. We listen for a generic navigate event from the WebViewTag, but we don't actually check whether it's loading in an iframe or not...

**Comment by esimkowitz** [comment]
We love a one-liner

**Comment by hahwul** [comment]
@esimkowitz, thanks for creating such a fantastic terminal! Really appreciate the swift fix on the issue I reported. Wishing you all the best!
