### ISSUE TITLE
[Bug]: Default keybindings file link leads to a 404

### ISSUE THREAD

**Issue by lorenzo-arena** [wavetermdev/waveterm#1512]
### Current Behavior

Clicking on the "default keybindings" link in the documentation leads to a 404 page.

### Expected Behavior

The page should show the default keybindings file.

### Steps To Reproduce

1. Open the documentation
2. Go to the "Custom keybindings" section
3. Click the link

### Wave Version

v0.10.1

### Platform

Linux

### OS Version/Distribution

Ubuntu 24.04

### Architecture

x64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
I think the doc you're referencing is from our old app, we don't currently have a way in the new app to apply custom keybindings.

**Comment by esimkowitz** [comment]
Could you provide the link you're clicking?

**Comment by lorenzo-arena** [comment]
> I think the doc you're referencing is from our old app, we don't currently have a way in the new app to apply custom keybindings.

You're right! I didn't know there was a legacy version and didn't pay attention to the doc link, which is https://legacydocs.waveterm.dev/reference/customKeybindings. I also asked in the Discord server and got the same response. But why were the keybindings made not customizable?

**Comment by esimkowitz** [comment]
We just haven't gotten around to it yet, definitely in the pipeline!

**Comment by esimkowitz** [comment]
I'll close this issue as not planned, but rest assured custom key bindings are coming soon!

**Comment by Gonkers** [comment]
I had no idea there was an "old app" and all of the search results still point to non-existent files

![image](https://github.com/user-attachments/assets/6def0aa2-8000-4753-8a0c-73b5fc3adeff)

Do you have a link to where I can learn about the "old" vs "new" apps?

**Comment by esimkowitz** [comment]
We have the following blog post explaining the change: https://waveterm.hashnode.dev/introducing-the-new-wave-terminal-v08

The new docs can be found at https://docs.waveterm.dev

**Comment by esimkowitz** [comment]
Unfortunately, dead links in Google are out of our control. If you find one, you can submit it to Google for takedown, I've been doing this as I come across them, but most should get filtered out over time.

**Comment by Gonkers** [comment]
> Unfortunately, dead links in Google are out of our control. If you find one, you can submit it to Google for takedown, I've been doing this as I come across them, but most should get filtered out over time.

Of course, I was just reporting how I came across this issue. I got the 404, then did an issue search.

> We have the following blog post explaining the change: https://waveterm.hashnode.dev/introducing-the-new-wave-terminal-v08
> 
> The new docs can be found at https://docs.waveterm.dev

Thanks for the info! I tried, very briefly, wave some time ago and I went back to my old term. I just happened to try it out again to see how it was turning out. Clearly big changes.
