### ISSUE TITLE
[Bug]: term:localshellopts does not work for Powershell

### ISSUE THREAD

**Issue by neradp** [wavetermdev/waveterm#1522]
### Current Behavior

When I set "term:localshellopts": "-nologo"  for "term:localshellpath": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" it does nothing. Powershell runs as normal.

### Expected Behavior

Powershell without "logo".

### Steps To Reproduce

When I set "term:localshellopts": "-nologo"  for "term:localshellpath": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" it does nothing. Powershell runs as normal.

### Wave Version

0.10.1

### Platform

Windows

### OS Version/Distribution

Windows 11 24H2

### Architecture

x64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Just checking, are you running on arm or was that a typo?

**Comment by neradp** [comment]
sorry it was a typo... amd64 👯

**Comment by esimkowitz** [comment]
The correct config format for this is:

```json
{
  ...
  "term:localshellopts": ["-NoLogo"]
}
```
