### ISSUE TITLE
[Bug]: open wave error 

### ISSUE THREAD

**Issue by Viking602** [wavetermdev/waveterm#1564]
### Current Behavior

open wave gui 
<img width="530" alt="image" src="https://github.com/user-attachments/assets/0d716fc0-2a9a-4530-b00d-8b85648e0209" />

### Expected Behavior

Normal startup

### Steps To Reproduce

 1.download wave 
2.Run wave 

### Wave Version

v0.10.1

### Platform

macOS

### OS Version/Distribution

15.1.1 (24B91)

### Architecture

arm64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Hmm I've never seen this before, do you have any special directory permissions on your home directory or on .config?

**Comment by esimkowitz** [comment]
Can you see if there's any logs in `~/Library/Application\ Support/waveterm/waveapp.log`? If you can send these logs to support@waveterm.dev, I can take a closer look and see if anything sticks out

**Comment by Viking602** [comment]
> Hmm I've never seen this before, do you have any special directory permissions on your home directory or on .config?

Thinks ! it was a permissions issue. I have fixed it.
