### ISSUE TITLE
[Bug]: blank window when creating a workspace and then immediately deleting it

### ISSUE THREAD

**Issue by thomasnew** [wavetermdev/waveterm#1567]
### Current Behavior

Client Version 0.10.1 (202412130332)
1 create a workspace.
2 delete the workspace.

![image](https://github.com/user-attachments/assets/920bab17-6c74-4830-b1fd-cf35c2b109b1)

### Expected Behavior

Expect to return the pre workspace.

### Steps To Reproduce

1 create a workspace.
2 delete the workspace.

### Wave Version

Client Version 0.10.1 (202412130332)

### Platform

Windows

### OS Version/Distribution

win 11

### Architecture

x64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Ah, this should be fixed in 0.10.2-beta.0

**Comment by thomasnew** [comment]
@esimkowitz nice job.  thanks.
Btw, I wonder how to config proxy for the web browser in wave?

**Comment by esimkowitz** [comment]
Like to proxy a webpage from a remote machine to the local web browser?

**Comment by thomasnew** [comment]
@esimkowitz , like "proxy switchyomege" plugin in chrome .

**Comment by esimkowitz** [comment]
Not sure I follow, can you open a new feature request?

**Comment by esimkowitz** [comment]
I'm gonna close this issue since the new release should fix your initial bug
