### ISSUE TITLE
[Bug]: Terminal crashes on Fedora, when reading ssh-config

### ISSUE THREAD

**Issue by Zinodel** [wavetermdev/waveterm#1568]
### Current Behavior

When I click the remote connect button or type `wsh ssh <remote-ip>`, the application crashes.
If I remove my `~/.ssh/config` file, the application works fine and the menu opens normally. 

The contents of the file do not matter. This error is reproduced with different ssh-config contents and even with an empty `~/.ssh/config`.

The format of the executable file is also irrelevant. I have tested it with Appimage, RPM and Snap. It crashes on each of them.

chmod attributes of ssh config, also doesn't matter. I tried with 0400, 0600, 0666. and even with 0777, the bug still exists.

The button:
![image](https://github.com/user-attachments/assets/4ea5cc1d-7391-4bb5-a169-d72674d593a4)

### Expected Behavior

Terminal opens the remote connections menu

### Steps To Reproduce

1. Fedora 41 (Another Fedora versions probably reproduce this too)
2. Run Waveterm
3. In terminal tab, click on remote connections button
4. Application get crash

### Wave Version

0.10.1, 0.10.2-beta.0 and 0.9.3

### Platform

Linux

### OS Version/Distribution

Fedora 41

### Architecture

x64

### Anything else?

Log lines is empty:
![image](https://github.com/user-attachments/assets/e225e939-73b6-4dcb-bf41-59ade82967fa)

But i make a stacktrace:

Strace of crashing:
[strace.log](https://github.com/user-attachments/files/18193569/strace.log)

This problem maybe related to `kevinburke/ssh_config` library. On 15563 line, you can see message about go panic:

```
read(44, "panic: can't handle Match directives\n\ngoroutine 453 [running]:\ngithub.com/kevinburke/ssh_config.(*Config).Get(0xc000134540, {0x121c868, 0x1}, {0x112a0ea, 0x4})\n\t/home/runner/go/pkg/mod/github.com/wavetermdev/ssh_config@v0.0.0-20241027232332-ed124367682d/config.go:421 +0x2be\ngithub.com/kevinburke/ssh_config.(*Include).Get(0xc000114000, {0x121c868, 0x1}, {0x112a0ea, 0x4})\n\t/home/runner/go/pkg/mod/github.com/wavetermdev/ssh_config@v0.0.0-20241027232332-ed124367682d/config.go:807 +0x176\ngithub.com/kevinburke/ssh_config.(*Config).Get(0xc0005283c0, {0x121c868, 0x1}, {0x112a0ea, 0x4})\n\t/home/runner/go/pkg/mod/github.com/wavetermdev/ssh_config@v0.0.0-20241027232332-ed124367682d/config.go:427 +0x20c\ngithub.com/kevinburke/ssh_config.findVal(0x0?, {0x121c868?, 0xc000481078?}, {0x112a0ea, 0x4})\n\t/home/runner/go/pkg/mod/github.com/wavetermdev/ssh_config@v0.0.0-20241027232332-ed124367682d/config.go:105 +0x34\ngithub.com/kevinburke/ssh_config.(*UserSettings).GetStrict(0x1c2d920, {0x121c868, 0x1}, {0x112a0ea, 0x4})\n\t/home/runner/go/pkg/mod/github.com/wavetermdev/ssh_config@v0.0.0-20241027232332-ed124367682d/config.go:240 +0xdf\ngithub.com/wavetermdev/waveterm/pkg/remote.NormalizeConfigPattern({0x121c868, 0x1})\n\t/home/runner/work/waveterm/waveterm/pkg/remote/connutil.go:343 +0x50\ngithub.com/wavetermdev/waveterm/pkg/remote/conncontroller.resolveSshConfigPatterns({0xc0004813b8, 0x2, 0xc00046f5c0?})\n\t/home/runner/work/waveterm/waveterm/pkg/remote/conncontroller/conncontroller.go:673 +0x906\ngithub.com/wavetermdev/waveterm/pkg/remote/conncontroller.GetConnectionsFromConfig()\n\t/home/runner/work/waveterm/waveterm/pkg/remote/conncontroller/conncontroller.go:752 +0x197\ngithub.com/wavetermdev/waveterm/pkg/remote/conncontroller.GetConnectionsList()\n\t/home/runner/work/waveterm/waveterm/pkg/remote/conncontroller/conncontroller.go:711 +0x27e\ngithub.com/wavetermdev/waveterm/pkg/wshrpc/wshserver.(*WshServer).ConnListCommand(0x2?, {0x2?, 0x0?})\n\t/home/runner/work/waveterm/waveterm/pkg/wshrpc/wshserver/wshserver.go:662 +0xf\nreflect.Value.call({0x1120820?, 0x1c93580?, 0x1129240?}, {0x112a076, 0x4}, {0xc0002b2288, 0x1, 0x1?})\n\t/opt/hostedtoolcache/go/1.23.4/x64/src/reflect/value.go:581 +0xca6\nreflect.Value.Call({0x1120820?, 0x1c93580?, 0xc0001de290?}, {0xc0002b2288?, 0x1129240?, 0x15e618b?})\n\t/opt/hostedtoolcache/go/1.23.4/x64/src/reflect/value.go:365 +0xb9\ngithub.com/wavetermdev/waveterm/pkg/wshutil.serverImplAdapter.func1(0xc000224e70)\n\t/home/runner/work/waveterm/waveterm/pkg/wshutil/wshadapter.go:119 +0x439\ngithub.com/wavetermdev/waveterm/pkg/wshutil.(*WshRpc).handleRequest(0xc0000c7500, 0xc0002cf180)\n\t/home/runner/work/waveterm/waveterm/pkg/wshutil/wshrpc.go:323 +0x557\ncreated by github.com/wavetermdev/waveterm/pkg/wshutil.(*WshRpc).runServer in goroutine 39\n\t", 65536) = 2775
```

But i dont shure about it.

On another Fedora 41 installation, the bug **reproduces**. 

On Gentoo Linux and macOS, it does **not reproduce**, and the connection management menu opens correctly with ssh configuration. 

If here is something, what i can do to help with solving a problem, tell me. I try to do my best to help.

### Questionnaire

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Ah you won't see the logs in the console, they'd be in ~/.local/share/waveterm/waveapp.log. Could you check here and email the contents to support@waveterm.dev?

The stack trace provides some context, but the logs will tell us the rest I hope

**Comment by esimkowitz** [comment]
This is fixed in the latest release

**Comment by Zinodel** [comment]
Everything works, thank you very much
