### ISSUE TITLE
[Feature]: UI optimizings/gpt/window size 

### ISSUE THREAD

**Issue by alexsupa597** [wavetermdev/waveterm#1586]
### Feature description

1-support the Gemini-2.0  and claude-3.5 
2-set default window size

### Implementation Suggestion

hi ~ there.

how about we support the Gemini-2.0  and claude-3.5 in the coming version?

I think they are more easier to use. 
and we can add a entrance to user for setting a default window size.
Every time I open it, I get a huge window.

**Comment by esimkowitz** [comment]
Following up on this, Claude is already supported (https://docs.waveterm.dev/ai-presets#anthropic-claude) and I'm planning on adding Gemini this week. I'm going to create a separate issue for default window size and close this issue as invalid, given it addresses too many asks at once.

**Comment by alexsupa597** [comment]
cool
