### ISSUE TITLE
is there a way to read alias defined in .zshrc file ?

### ISSUE THREAD

**Issue by alainib** [wavetermdev/waveterm#159]
**Is your feature request related to a problem? Please describe.**
i use `iTerm` with `ohMyZh` and have lot of alias in `.zshrc` 

is there a way to load them on start of wave ? 
thanks

**Comment by sawka** [comment]
Not yet.  We plan on supporting zsh natively (at which point we'll read your .zshrc and load your zsh environment).  Right now though you'd have to transfer any aliases to your .bash_profile, and they would have to follow bash syntax rules for them to work.

**Comment by dylanpistachi** [comment]
It still doesn’t work for me, despite several configurations on bash. Possible to have documentation to know how to do exactly?

**Comment by nickali** [comment]
Is supporting aliases in .zshrc still on the roadmap?

**Comment by sawka** [comment]
Ah, forgot to close this bug.  Wave now supports zsh and bash (and will detect which shell is your default).  If you use zsh then your aliases will be loaded!

**Comment by nickali** [comment]
Cool, it does work. But it looks like they aren't available for completions?
