### ISSUE TITLE
[Bug]: The scroolling bar does not appear on the ‘wave ai’ widget

### ISSUE THREAD

**Issue by cyrilleby** [wavetermdev/waveterm#1591]
### Current Behavior

The scroolling bar does not appear on the ‘wave ai’ widget, 
And when you ask a question and the answer goes beyond the window size, the answer is not visible.

### Expected Behavior

view the screen recording

### Steps To Reproduce

https://github.com/user-attachments/assets/60ae55eb-04ad-4ef1-b7a1-ccd1dc656535

### Wave Version

v0.10.3

### Platform

Windows

### OS Version/Distribution

11

### Architecture

x64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Fixed in #1588, should go out in a patch release today

**Comment by cyrilleby** [comment]
Thanks, sorry for the duplication

**Comment by esimkowitz** [comment]
No duplication here, @oneirocosm just caught the bug already thanks to a Discord user :)

**Comment by esimkowitz** [comment]
this should be fixed in 0.10.4-beta.1

**Comment by esimkowitz** [comment]
0.10.4 is now released, this is fixed
