### ISSUE TITLE
Cannot Edit Connection Port Number (when creating a connection)

### ISSUE THREAD

**Issue by sawka** [wavetermdev/waveterm#162]
On certain keyboard layouts (mostly on Linux), the SSH Port field is not accepting input correctly when creating a connection.  This means users cannot create connections to non-standard port numbers.

We believe this is an issue with our numeric input field and keyCode processing that is inconsistent between MacOS and Linux (and international keyboard layouts).

**Comment by esimkowitz** [comment]
What if we used the browser-native _input type=number_ field? Would this satisfy the internationalized keyboards?

**Comment by oneirocosm** [comment]
Closing this as it should be fixed by #166
