### ISSUE TITLE
TestDriver pipeline fails for non-org members

### ISSUE THREAD

**Issue by esimkowitz** [wavetermdev/waveterm#1621]
The TestDriver pipeline fails if the user who created a PR does not have GitHub Secrets permissions. This makes sense, but it also limits our ability to test external contributions before merging them.

**Comment by esimkowitz** [comment]
@chottuthejimmy @ianjennings is there a way we can do this where we don't need to use a GitHub Secret to queue the jobs to TestDriver?

**Comment by esimkowitz** [comment]
Seems like we can be using the `pull_request_target` trigger to get around this. It'll use the workflow files as they're defined in our main, rather than as defined in the forked repo, which should mitigate secret leakage or misuse. This way, we can still use GitHub Secrets to manage the access token.

https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/

**Comment by ianjennings** [comment]
Yes and there are a few other options listed here as well:

https://stackoverflow.com/questions/76975408/how-to-pass-a-secret-from-a-forked-github-repo-to-source-repo

**Comment by esimkowitz** [comment]
I think the risk of `pull_request_target` is acceptable in our case. We only expose the TestDriver access token, which we can always rotate if we notice it's being abused, we can specify in the workflow definition that we only want to grant it secrets access, and we have "require approval for all outside contributors" checked already.

**Comment by esimkowitz** [comment]
Okay I think the linked PR addresses any security concerns with using `pull_request_target`

**Comment by esimkowitz** [comment]
I ended up actually switching so the pipeline is now broken into a `pull_request` trigger and a `workflow_run` trigger
