### ISSUE TITLE
bashrc completion does not work

### ISSUE THREAD

**Issue by dylanpistachi** [wavetermdev/waveterm#172]
Hello,
I would like to know how to have the auto-completion I have in my . bashrc file on Wave.

I saw that we could modify the environment variable WAVESHELL but it does not give the expected result. Someone to help me, please?
I specify that these are custom auto-completion in order to access my servers via aliases

Thanks!

**Comment by sawka** [comment]
Hi, thanks for submitting!  Wave Terminal handles all keyboard input locally.  That means we do not use any bash/zsh completion code to run our completions.  There are definitely places where bash/zsh (especially zsh) has more advanced completion code than we do, but we are working on closing the gap.  In fact we're working on some really exciting new completion code that should be deployed in the next couple of weeks.

If you don't mind sharing what your custom completion code does (if you share you bash scripts in a gist or comment that could be really helpful!) we can take a look to see if that is something we'll be able to support in the future.
