### ISSUE TITLE
Format of user@host should accept 'DOMAIN\username'@host

### ISSUE THREAD

**Issue by PatBoEPFL** [wavetermdev/waveterm#173]
Hello,

We use a AD domain group for our administrators to connect to our NetApp NAS. This implies that the format or the user is domain\username. This works perfectly fine in PuTTY, iTerm2, openssh.

The user@host verification should include following forms as valid:

- 'domain\username'@host
- domain\\username@host

Thank you very much in advance for your consideration of my request,
Patrice

**Comment by oneirocosm** [comment]
I have loosened the requirements to allow forward slashes in user names with pull request #209. I do not know if that is sufficient to solve the problem, but it is what we are able to do in the short term. I'm going to mark this as closed for now, but please feel free to open it again if there are issues of this sort in the future.

**Comment by oneirocosm** [comment]
as a note, this will not be available in the next release (should be 0.6.0), but it can be found in the main github branch until then
