### ISSUE TITLE
I can't archive, delete workspaces

### ISSUE THREAD

**Issue by raiden70** [wavetermdev/waveterm#174]
After installing the app, i added multiple workspaces and i can't archive or delete them i got this error: Error: /session:purge session "" not found
and i've just notice an overflow of a text panel in the modal of updating status connections

**Comment by sawka** [comment]
Oh no!  that's a new bug.  Thanks for pointing that out, we'll try to issue a quick patch.

**Comment by sawka** [comment]
Didn't mean to close this issue since the fix hasn't been actually sent out in a release yet.  But it is now committed to main, so it will be in v0.5.3.  Given the severity of this issue, I'll probably cut that release tonight or tomorrow.
