### ISSUE TITLE
Sudo does not persist on Linux version

### ISSUE THREAD

**Issue by FallconTXoC** [wavetermdev/waveterm#180]
**Describe the bug**
Wave seems to start a new shell session at each user input without giving the ability to resume a previous shell session, this leads to sudo authentication to not persist and asks for password/fingerprint at each sudo command.

**To Reproduce**
1. Open Wave
2. Go to any workspace
3. Select any tab
4. Write a command with sudo (eg. `sudo whoami`)
5. Write another command with sudo

**Expected behavior**
Shell should only ask once for sudo authentication and then persist the authentication for a given time (eg. on Ubuntu the default timeout is 15 minutes).

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 22.04.3 / amd64
 - Version: v0.5.1

**Comment by sawka** [comment]
Thanks for submitting.  This is on our radar and we plan to put some time into working with how connections are handled (including how they handle sudo) in this release.  No guarantees because we haven't scoped all of the work yet, but we hope to have this fixed in early January.

**Comment by FallconTXoC** [comment]
This is not specifically related to connections though, this sudo handling issue happens locally too when using Wave as a regular terminal.

**Comment by sawka** [comment]
This is now fixed as of v0.7.4!
