### ISSUE TITLE
Make tab closing easier

### ISSUE THREAD

**Issue by FallconTXoC** [wavetermdev/waveterm#181]
**Is your feature request related to a problem? Please describe.**
I find the current way of closing tabs kind of annoying, having to click on the tab to open a menu then click "delete" _then_ click "yes" is time consuming and contrasts with the philosophy of Wave which allows to do most things by shortcuts and commands.

**Describe the solution you'd like**
Make a shortcut or a command to easily close a tab, perhaps even avoid asking confirmation when using the command.

PS: idk if it's an intended feature but the tab's menu does not automatically close when deleting the tab, adding an extra step to the deletion process.

PS²: I'm using Linux, in case this behavior is specific to this version.

**Comment by sawka** [comment]
Thanks for submitting.  Definitely agree.  We'll work on adding a keyboard shortcut for sure and fix the bug around the popup not closing.

In the mean time, one workaround for you is to use Wave's slash commands.  To delete a tab you can run: `/screen:purge`(and to archive you can run `/screen:archive`).  No annoying popup, and it works directly from the cmd input window (almost like the `clear` command, except it also kills off the entire tab).

**Comment by FallconTXoC** [comment]
Oh yeah I missed these commands in the doc, thanks for letting me know.

**Comment by sawka** [comment]
Added a PR for this.  Cmd-W will not close tab.  This should go out in the next release.

For now it still pops up a "confirm" message dialog.  But that dialog can be controlled with the keyboard ("return" is "ok" and "esc" is "cancel").  So you can delete a tab by hitting Cmd-W and then Return.

In the future I want to remove the confirm dialog box.  The plan will be to allow a 5-second "undo".  So you would hit Cmd-W, the tab would be deleted.  But a small UI indicator (somewhere) would come up (like in Gmail) that says, "Undo?".  And if you clicked that indicator (or hit some other hotkey, maybe Cmd-Z) it would undo the delete and bring back the tab.  For now though I want the confirm dialog so I don't accidentally delete my multi-thousand command tabs :)

**Comment by FallconTXoC** [comment]
Alright thanks ! Good idea for the "undo" ability, though why not make it app wide with no time limit but instead action limit ? Kind of like allowing people to undo their last action on the app (delete tab, create new workspace, create new tab...). This could prove useful in some cases, and will avoid people realizing few minutes later that they shouldn't have deleted the tab.

**Comment by sawka** [comment]
Hmm, I'm not sure how to balance an unlimited undo with actual deletion?  For the time period that we offer an undo we have to keep the data around somewhere (otherwise we can't restore it).

If we wanted a more unlimited undo, maybe we'd need a concept of "trash".  So when you want to not be able to undo anymore you can "clear your trash"?  Hard to balance all of this though since I also don't want things to become too complicated :)

**Comment by FallconTXoC** [comment]
I meant more like you can undo your last action, not all of them, of course making an unlimited undo would take a lot of memory and that would be unnecessary anyway.
