### ISSUE TITLE
Encoding problem with Chat GPT

### ISSUE THREAD

**Issue by gnodet** [wavetermdev/waveterm#190]
**Describe the bug**
It seems there's an encoding problem when displaying answers from Chat GPT

**To Reproduce**
1. Run `/chat comment est fabriqué le café décafféiné ?`
2. See printed answer where all French accents are replaced with `??`

**Screenshots**
<img width="1136" alt="image" src="https://github.com/wavetermdev/waveterm/assets/84022/c4f12fab-ca01-4c24-bb30-2af5bcbbcff1">

**Comment by sawka** [comment]
Thanks for submitting!  We're working on internationalization issues for the next release (high priority).  Didn't realize it also affected the chat gpt responses.  Thanks for bringing this to our attention.

**Comment by oneirocosm** [comment]
Closing since this has been fixed with the merge of pull #209. It is available in v0.6.0
