### ISSUE TITLE
Can't delete or archive workspace or tab

### ISSUE THREAD

**Issue by chrislatimer** [wavetermdev/waveterm#192]
**Describe the bug**
Whenever I try to delete a workspace or tab I get the error message: `Error: /session:purge session "" not found`

**To Reproduce**
<img width="672" alt="image" src="https://github.com/wavetermdev/waveterm/assets/831081/c611e6ff-7fcd-45a3-adb5-b3b149deb7e8">

<img width="533" alt="image" src="https://github.com/wavetermdev/waveterm/assets/831081/cedc948f-f608-4374-a42c-b697753cfcad">

<img width="660" alt="image" src="https://github.com/wavetermdev/waveterm/assets/831081/9f3d1c7b-2a09-401f-9898-2bb50b29dd9c">

**Expected behavior**
Workspace should go away or be hidden.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 13.4 (22F66)

**Comment by sawka** [comment]
Thanks for submitting.  This is fixed in v0.5.3 (we pushed a quick v0.5.3 specifically to fix this bug).
