### ISSUE TITLE
Cannot create multiple remote connections with same canonical name and different ports

### ISSUE THREAD

**Issue by Elliot-Construct** [wavetermdev/waveterm#204]
**Describe the bug**

I have encountered a bug when trying to use WaveTerm to connect to multiple machines on the same url with the same credentials, but different ports. For example, I want to connect to user@domain:22 and user@domain:82. However, WaveTerm does not allow me to create new remote connections that use the same canonical name but a different port. It gives me an error message saying “cannot create remote “user@domain”: duplicate canonical name “user@domain”: cannot create new remote”. This prevents me from accessing different machines that share the same url and credentials.

**To Reproduce**
1. try to connect to multiple machines on same url with same credentials, port 22 and port 82.
Error: cannot create remote "user@domain": duplicate canonical name "user@domain": cannot create new remote

**Expected behavior**

The ability to create new remote connections that use the same canonical name but a different port.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS/Linux, x64 or arm64] Linux - Ubuntu - WSL

**Comment by sawka** [comment]
thanks for submitting.  as canonicalname is the key for remotes this isn't possible right now.  i think we can fix this by adding non-standard port numbers to the canonical name.

as a workaround for now, you can add an entry in your /etc/hosts file to alias domain and then you'll be able to add a new connection.

**Comment by oneirocosm** [comment]
Closing since this has been fixed with the merge of pull request #209

**Comment by oneirocosm** [comment]
as a note, this will not be available in the next release (should be 0.6.0), but it can be found in the main github branch until then
