### ISSUE TITLE
What is mshell installed on a remote?

### ISSUE THREAD

**Issue by samuelba** [wavetermdev/waveterm#208]
What is `mshell` installed on any remote? I could not find any information about it in any documentation. If you just install something on a remote without even asking, it would be at least nice to know what it is and why it is required. Thank you.

**Comment by esimkowitz** [comment]
`mshell` is the same as [`waveshell`](https://github.com/wavetermdev/waveterm/tree/main/waveshell). It is a local agent that manages the pty sessions, etc. on your remote machine. This communicates with the main Wave app over SSH. It does not open any additional ports or send us any telemetry.

We understand the concern about installing things on remote computers unprompted. We are planning to document this agent more in and we are going to add an informational prompt in the "New Connection" pane that will require approval before we install it.

**Comment by samuelba** [comment]
Thank you for the explanation.

**Comment by sawka** [comment]
I've added a FAQ entry to address this question.  https://docs.waveterm.dev/reference/faq#what-is-mshell-waveshell-why-does-it-need-to-be-installed-on-machines-i-connect-to
