### ISSUE TITLE
Outdated dependency referred in installation guide for WSL

### ISSUE THREAD

**Issue by yaner-here** [wavetermdev/waveterm#256]
## **Describe the bug**

[Wave installation guide for WSL](https://docs.waveterm.dev/quickstart) refers to `libgconf-2-4` as a dependency, but many Linux distributions have deprecated it in their package sources. More details in Additional Context.
```sh
sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev
```

Developers from [Cypress](https://github.com/cypress-io/cypress/issues/27972#issuecomment-1761221783) updated their installation guide and I found that it also works for Wave.
```sh
apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
```

## **To Reproduce**
```shell
$ sudo apt install libgconf-2-4
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libgconf-2-4
```

## **Expected behavior**
None

## **Screenshots**
None

## **Desktop (please complete the following information):**
 - OS: Windows WSL
 - Version: Kali Rolling Distribution in Microsoft Store

## **Additional context**

Regarding the maintenance of `libgconf-2-4`:
- Deprecated by [Debian](https://bugs.debian.org/1043068)
- Still maintained by [Ubuntu Universe channel](https://packages.ubuntu.com/search?keywords=libgconf-2-4)
- Deprecated by [Kali](https://pkg.kali.org/news/547356/gconf-326-8-removed-from-kali-rolling/)

**Comment by Olivier-Pickup** [comment]
```
sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev
```
didn't work for me either givving me a `Trace/breakpoint trap` message

```
apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
``` worked !

**Comment by gonzolively** [comment]
Thank you for commenting @Olivier-Pickup , I have just closed this issue with the latest push to our docs.

Thanks again for your contribution!
