### ISSUE TITLE
Increase height of top bar 

### ISSUE THREAD

**Issue by panoskyriakis** [wavetermdev/waveterm#275]
**Is your feature request related to a problem? Please describe.**
<img width="671" alt="Screenshot 2024-02-03 at 4 04 58 PM" src="https://github.com/wavetermdev/waveterm/assets/134383572/868e4785-4f7f-43c8-ad6e-0091882a7619">

The top bar is kind of small and you have to be very percice if you want to drag-and-drop the window. 

**Describe the solution you'd like**
I'd recommend increasing the size of the top bar. Even making the height adjustable to some extend.

**Comment by sawka** [comment]
We changed how the top bar is rendered in the new UI.  Now there is always a drag area on the left (between the traffic lights) and a drag area to the right of the tabs.  This will ship with the new UI in v0.7.0
