### ISSUE TITLE
Unable to CD into any other folder if the current folder is deleted

### ISSUE THREAD

**Issue by tusharnath31** [wavetermdev/waveterm#278]
**Describe the bug**
Unable to CD into any other folder if the current folder is deleted

**To Reproduce**
1. cd into some folder (eg: /Users/user1/Desltop/demo/test )
2. delete the folder "demo" from finder
3. now if I try to cd to Desktop or any other existing forder, i get an error

**Expected behavior**
User should be able to switch the directory to 

**Screenshots**
<img width="1043" alt="image" src="https://github.com/wavetermdev/waveterm/assets/30938602/41fd781c-5f0c-4d9b-81d4-1110c45e4814">

**Desktop (please complete the following information):**
 - OS: MacOS x64 
 - Version  v0.6.1

**Additional context**

**Comment by sawka** [comment]
The workaround for this is to use the meta command /reset.  that will reinitialize your session and put you back in your home folder.

in the future we want to be able to detect this situation and provide a better workaround.

**Comment by sawka** [comment]
next version will have a better fix.  we detect this case and show a special error message that prompts you to run a new slashcommand `/reset:cwd` which will reset (just) your cwd.
