### ISSUE TITLE
"Markdown Preview" command (CMD +P) is duplicate with "switch to tab" shortcut.

### ISSUE THREAD

**Issue by gonzolively** [wavetermdev/waveterm#284]
**Describe the bug**
When using `codeedit` to view markdown files, I issue a "CMD +P" command to use the markdown preview feature, but instead I get a "switch to tab" modal. Upon searching Wave shortcuts I do see "CMD +P" as the shortcut listed for tab switching. Consider switching the shortcut for one or the other.

**To Reproduce**
1. Type `codeedit` to view a file...ex "`codeedit README.md`
2. Issue `CMD + P` shortcut
3. Then presented with a "tab switcher" modal

**Expected behavior**
When I am using `codeedit` to view a file and issue the appropriate shortcut it should open a preview pane, instead I have to manually click that preview pane button as the "tab switcher" is what opens instead of the preview pane.

**Screenshots**
* [Screenrecording](https://github.com/wavetermdev/waveterm/assets/990275/7ac74bc0-51c7-4d24-bf03-d17caf9e0947)

**Desktop (please complete the following information):**
 - OS: MacOS Sanoma 14.3.1 (23D60)
 - Version: v0.6.1 (20240131-063625)

**Comment by sawka** [comment]
Great catch.  Didn't see the conflict of the two keybindings.  (1) we shouldn't have these conflicting keybindings to begin with.  (2) the events are not processed correctly.  if the codeviewer is open it should have grabbed the Cmd-P first (overriding the global keybinding).

We're working on a better way to handle keybindings (and customize) them.
