### ISSUE TITLE
Window controls missing after entering fullscreen

### ISSUE THREAD

**Issue by gonzolively** [wavetermdev/waveterm#285]
**Describe the bug**
When I put Wave into full screen mode the window controls for "maximize" and "minimize" (Green and yellow button respectively) disappear, forcing me to close the terminal and re-open if I wish to resize the windows.

**To Reproduce**
1. Open Wave
2. Click on fullscreen button
3. Unable to click maximize so I'm forced to click the "close" (red) button
4. Restart Wave to resize

**Expected behavior**
All window controls should be available to me no matter the state of the window

**Screenshots**
* [Screenrecording](https://github.com/wavetermdev/waveterm/assets/990275/68ab476f-d00b-4107-a0be-8d234e384cf9)

**Desktop (please complete the following information):**
 - OS: MacOS Sanoma 14.3.1 (23D60)
 - Version: v0.6.1 (20240131-063625)

**Comment by esimkowitz** [comment]
Weird, I see this too. I think this is probably some Electron setting we're failing to implement. A workaround is to use the "View -> Toggle Full Screen" menu option

**Comment by oneirocosm** [comment]
Fixed in v0.7.0
