### ISSUE TITLE
Connection dialog box appears to hang when connecting to remote session requiring password

### ISSUE THREAD

**Issue by gonzolively** [wavetermdev/waveterm#286]
**Describe the bug**
Upon setting up a new remote connection in the connections tab, and then clicking the "connect" button the connection appears to hang without any indication why. Upon further inspection, it was a faulty-sized connection window that made it hard to see the connection wizard was waiting for user input (password in my case), and was only able to discover the issue by issuing a "CMD +A" and "CMD +C" to select and copy all text in the connection window, then paste it into a text editor to see all the output.

**To Reproduce**
1. Click the "Connections" tab in the left sidebar
2. Click "New Connection"
3. Enter host details
4. Click "Connect"
5. The connection dialog box is unable to display all contents, the connection appears to hang.

**Expected behavior**
I expect to see all connection output, especially when requesting user input.

**Screenshots**
* [Screenshot 1](https://github.com/wavetermdev/waveterm/assets/990275/97901a2b-d8cd-4ae6-87ef-4290ea912b25), the connection window with limited output
* [Screenshot 2](https://github.com/wavetermdev/waveterm/assets/990275/0ce05e99-f50e-4f26-914e-6905d9a4f8ce), the copy/pasta into a text editor to see full output.

**Desktop (please complete the following information):**
 - OS: MacOS Sanoma 14.3.1 (23D60)
 - Version: v0.6.1 (20240131-063625)

**Additional context**

**Comment by sawka** [comment]
Various modal resizings have broken the terminal window view.  We're working on a fix for v0.7.0.  (1) we'll resize the modal / terminal window to actually fit inside of the modal window.  (2) there seems to be another problem where the terminal output is not being automatically scrolled to the bottom.

**Comment by oneirocosm** [comment]
@adred I added something for this in v0.7.0. Could I get you to confirm that it's fixed?
