### ISSUE TITLE
Cannot connect to SSH-Server with key+password privatekey

### ISSUE THREAD

**Issue by timo1302** [wavetermdev/waveterm#300]
**Describe the bug**
It is not possible to connect to an SSH-Server with a custom SSH-Port by privatekey+password.

**To Reproduce**

1. Create connection Type:
![setup_wave_terminal](https://github.com/wavetermdev/waveterm/assets/28393716/96c5c423-d8c3-4e5d-8b8b-a1ec887e5eae)

2. Start connection:
![connection_start](https://github.com/wavetermdev/waveterm/assets/28393716/c6c1f993-a26b-4c23-a620-fdf411eef672)

3. Enter Terminal:

![fail_wave](https://github.com/wavetermdev/waveterm/assets/28393716/ac7aa997-b5d1-443e-ac02-292587af32a7)

**Desktop (please complete the following information):**
 - OS: Linux, x64 Fedora 39 KDE
 - Version Client Version v0.6.2 (20240210-225244)

Is the problem already known and how can i fix that?
Error-Message: "Error: /connect error: remote "root@X.X.X.X:45210" cannot switch to archived remote

**Comment by oneirocosm** [comment]
Thanks for bringing this up!  I think I have some idea where this might be coming from, but I want to check a couple things.
- Did you previously have another remote with the same hostname? If so, did it have a different port?
- Did you previously have another remote with the same alias?

**Comment by oneirocosm** [comment]
Just as an update, there is a fix for this in the next release.
