### ISSUE TITLE
Add currently active python env in UI

### ISSUE THREAD

**Issue by panoskyriakis** [wavetermdev/waveterm#304]
**Is your feature request related to a problem? Please describe.**
Python/ML developers usually like to know which is the currely active python environment. This could be a conda/pyenv/etc environment, like shown bellow:

<img width="855" alt="Screenshot 2024-02-19 at 4 31 51 PM" src="https://github.com/wavetermdev/waveterm/assets/134383572/0d8ac355-b32e-415c-91f3-d319dfa4a5e7">

**Describe the solution you'd like**
Wave could identify if there's a python env manager and if so show the name of the currently active env, similarly to git branches.

**Comment by esimkowitz** [comment]
This is completed now with 0.7.0
