### ISSUE TITLE
History filters dropdowns don't automatically close

### ISSUE THREAD

**Issue by FallconTXoC** [wavetermdev/waveterm#330]
**Describe the bug**
Filters dropdowns don't close automatically when clicking outside in the History view.

**To Reproduce**
1. Go to the history view
2. Click on a filter that opens a dropdown
3. Click anywhere outside of this dropdown in the Wave window
4. See that the dropdown remains open

**Expected behavior**
The dropdown should automatically close when clicking outside.

**Desktop (please complete the following information):**
 - OS: Linux x64 (Ubuntu 22.04)
 - Version v0.6.2

**Comment by sawka** [comment]
Fixed in v0.7.0 (switched history dropdowns to the new style of dropdown)
