### ISSUE TITLE
Changed code signature in macOS version 0.7.0

### ISSUE THREAD

**Issue by suschizu** [wavetermdev/waveterm#422]
**Describe the bug**
The code signature has changed between version 0.6.3 and 0.7.0

can you please confirm this @sawka?

EXPECTED 'G Michael Sawka (VYQ48YC2N2)' 
FOUND 'Michael Sawka (8M47V3YG4N)'

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 0.7.0

**Comment by esimkowitz** [comment]
Yes this is expected, we were using @sawka's personal Apple ID before to sign our macOS binaries. We are now using one under a work email, but it still needed a real name for the account. We are working to get our organization account configured, at which point our binary signature will change again, this time for good, to "Command Line Inc"

**Comment by suschizu** [comment]
great - thanks for the clarification here 🙌
