### ISSUE TITLE
Telemetry: Provide Details on Which Data is Collected

### ISSUE THREAD

**Issue by reform-chipper** [wavetermdev/waveterm#423]
Please provide a precise and up-to-date list of what data is collected with Telemetry enabled, either on the website or in the UI. I want to help this project, but I could only turn Telemetry on for my personal device. On my work device I wouldn't dare without knowing what exactly is happening in the background. 

Even that infamous competitor which prevents their terminal from being used without logging in provides a precise list.

**Comment by oneirocosm** [comment]
This one's on me. It was on my todo list and got away from me. I'll get one together ASAP. And then will add a link to the first-time launch screen as well.

**Comment by oneirocosm** [comment]
Alright, the telemetry page has been added to our [docs website](https://docs.waveterm.dev/reference/telemetry). Now I just need to add a link to it on the welcome page.

**Comment by reform-chipper** [comment]
Looks good, thanks! I think I will be able to reenable telemetry. I am actually surprised you don't collect more precise data with regards to the UI usage, considering novel UI is the main selling point of the terminal.
