### ISSUE TITLE
Rename Workspaces Easily

### ISSUE THREAD

**Issue by reform-chipper** [wavetermdev/waveterm#425]
Renaming a workspace requires a user to hover over the workspace title in the sidebar and click the button that appears, and then click on the edit button in the new window that pops up. I think this could be made easier. 

Suggestions (can be both):

1) When hovering over the workspace title in the sidebar, a pencil icon appears on the right. Clicking on this icon enters the edit mode on the workspace title. 

or

2) Double clicking on the workspace title enters the workspace name edit mode

**Comment by INDHU1402** [comment]
Hello @esimkowitz 
I came across this issue and would like to work on resolving it. Can you assign it to me ?

**Comment by esimkowitz** [comment]
Ah, this is for our old app, I believe it is no longer relevant. We completely redid our app this summer and just shipped our new workspaces feature, which pretty much exactly aligns with the suggested implementation here

**Comment by esimkowitz** [comment]
I will close this issue for now as I believe we’ve satisfied the ask here, but please open a new one if you’ve got an idea on how our implementation can be improved!

**Comment by INDHU1402** [comment]
No issues, thanks for the reply :)
