### ISSUE TITLE
box cursor color in vim does not get set correctly

### ISSUE THREAD

**Issue by ntietz** [wavetermdev/waveterm#442]
**Describe the bug**

When using vim, the box-cursor represents where you are. This is typically set to be a contrasting color from the background. When using a dark theme in Wave and using the default color scheme in vim, this is set correctly. When using a theme with a white background, however, the cursor appears to be missing and you cannot see the location of your cursor.

**To Reproduce**

1. Set theme to Light.
2. Open vim with no plugins: `vim --clean`
3. Observe that the box cursor is not visible.
4. Set the color scheme to blue with `:colo blue`. Observe that the box cursor is visible.

**Expected behavior**

The box cursor color should contrast with the background and should be set if a vim colorscheme sets it.

**Screenshots**

![image](https://github.com/wavetermdev/waveterm/assets/808964/4da2c93c-3250-4e9e-acff-6307af4a3aa5)

**Desktop (please complete the following information):**
 - OS: Fedora 38 (Workstation Edition)
 - Version: 0.7.0 20240308-220638

**Additional context**

It's possible this is a vim configuration issue, but since I can reproduce it with none of my config and with default colorschemes that behave correctly in other terminals, I suspect it's an interaction with Wave in particular. But happy to be wrong if there's a solution, looking forward to using Wave!

**Comment by sawka** [comment]
Thanks for submitting!  We're working out a couple of kinks in light mode.  Just reproduced the bug on my dev environment so we should be able to get this patched quickly.

**Comment by sawka** [comment]
fixed in v0.7.1
