### ISSUE TITLE
Use of "module load xxx" in wave do not work

### ISSUE THREAD

**Issue by stheil15** [wavetermdev/waveterm#478]
Using Module environement do not work in Wave.

When you use a `module load xxx`  command it applies only in the executed command, not for the folllowing ones.

**Comment by sawka** [comment]
Thanks for the bug report.  I'll add support for this in the next patch release.

For now though, there is a workaround.  If you add "[rtnstate=1]" (the "=1" is optional, so it could also be written as "[rtnstate]") as a wave parameter before your command it should update the state correctly:

`[rtnstate=1] module load xxx`
