### ISSUE TITLE
Bug: Git Branch Doesn't Update

### ISSUE THREAD

**Issue by milldr** [wavetermdev/waveterm#581]
**Describe the bug**
The git branch listed is not correct. When you enter a directory and change the branch, the listed branch does not change. 

However, you can leave the directory and come back and it will be correct.

**To Reproduce**
1. Open any repo
2. Look at the given branch, it should be correct now
3. Change your branch - `git checkout -b foo`
4. The listed branch is not correct now
5. Leave that directory
6. Return to the directory
7. Now it's correct

**Expected behavior**
The branch should update when changed

**Screenshots**
![CleanShot 2024-04-17 at 14 47 29](https://github.com/wavetermdev/waveterm/assets/14060048/b419819c-737e-46ab-b4d7-86398406afb8)

**Desktop (please complete the following information):**
 - OS: macos 14.2 (23C64) m3
 - Wave: Client Version 0.7.2 (20240329-220114)

**Additional context**

**Comment by martinjirku** [comment]
Same for me:
- OS: 14.4.1 (23E224)
- Wave: Client Version 0.7.2 (20240329-220114)

Updates to the current branch, when I switch the workspace and come back to the original workspace.

**Comment by sawka** [comment]
This should be fixed as of Wave v0.7.4.  There was an issue where zsh was not running our exittrap as expected (I didn't notice at first because bash did run the exittrap).
