### ISSUE TITLE
linux build fails on step: scripthaus run electron-rebuild

### ISSUE THREAD

**Issue by psgandalf** [wavetermdev/waveterm#584]
When trying to build on Ubuntu following https://github.com/wavetermdev/waveterm/blob/main/build-linux.md
The step:  scripthaus run electron-rebuild gives an error:
.electron-rebuild: row 3: node_modules/.bin/electron-rebuild: the file or folder doesn't exist.
 - OS: Ubuntu 22.04 LTS
 - Version [e.g. v0.5.0

Adding:
"electron-rebuild":"3.2.9", to the devDependencies in package.json fixes the problem.

**Comment by esimkowitz** [comment]
Thanks for pointing this out @psgandalf! Do you want to open a PR to fix this? If not, I can do it for you.

**Comment by psgandalf** [comment]
I'l try to do a PR.

**Comment by esimkowitz** [comment]
Thank you for your contribution!! I've merged your PR, I'm closing this as resolved.
