### ISSUE TITLE
Respect the XDG base directory specification

### ISSUE THREAD

**Issue by quazar-omega** [wavetermdev/waveterm#677]
**Is your feature request related to a problem? Please describe.**

Right now, with the latest Appimage, Waveterm created a `.waveterm` directory directly under my home.
Though, on top of that, I also saw that it actually created a `Wave` directory under `$XDG_CONFIG_HOME`, I'm not sure why both need to exist, is there a reason for this?

**Describe the solution you'd like**

Ideally Waveterm should respect the XDG configuration of the user and place all its configurations, cache, state, etc. under the appropriate directories.

**Comment by esimkowitz** [comment]
closing in favor of #1025

**Comment by quazar-omega** [comment]
Awesome! Thanks for working on it :)
