### ISSUE TITLE
Wrong alt text

### ISSUE THREAD

**Issue by reform-chipper** [wavetermdev/waveterm#682]
**Describe the bug**
Alt text of what I believe is something related to AI says "restart command" instead

**Screenshots**
<img width="232" alt="image" src="https://github.com/wavetermdev/waveterm/assets/162800380/524067ac-465b-4dfa-b0dc-91ddb6c84359">

Client Version 0.7.6 (20240615-002636)

**Comment by luckrnx09** [comment]
fixed it ☝️

**Comment by vinugawade** [comment]
Hi,

I'm using Ubuntu and encountered the same issue with the incorrect alt text. I'm currently on version `0.7.6 (20240615-002644)` of Waveterm. Here's what I saw:

![Screenshot from 2024-08-23 22-47-52](https://github.com/user-attachments/assets/94abf2bc-63cb-48f3-ad05-ec44b5ac1782)

I checked the related PR and saw that it’s supposed to be fixed. To ensure I was on the latest version, I updated my system, uninstalled the current version, downloaded the new `.deb` from the latest release, and restarted my system. However, the issue persists, and it seems I was already on the latest version.

Upon further checking, it looks like the latest release doesn’t include PR #685, which addresses this issue. Could you let me know when the next version with this fix will be released?

Thanks!
