### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by the-spyke** [wavetermdev/waveterm#71]
**Is your feature request related to a problem? Please describe.**

I would like to be able to install the app without adding files to the root file system.

**Describe the solution you'd like**

Flatpak is the modern package format for Linux and is disto-agnostic. It provides a sandbox, so users are more protected installing your software. And for the developer it allows supporting dozens of different Linux distos with just a single package. It also comes with a wonderful "store" for users to discover your app and install it: https://flathub.org/

Please consider distributing the Wave Terminal on Flathub.

**Comment by ebits21** [comment]
I came to request this as well. 🙂

**Comment by sawka** [comment]
Hi @the-spyke thanks for submitting the issue.  Linux packaging is definitely on the todo list.  Do you have a strong preference for flatpak over snap?  I had thought to start with snap, but your issue + some quick googling is maybe changing my mind...

**Comment by the-spyke** [comment]
@sawka You may also support both Flatpak and Snap.

This is my opinion. I moved away from Snap last year (even if I still use Ubuntu). The reason being Snap is very slowly developed. It took them 4 years to implement refresh awareness, because of lack of which apps may corrupt data from time to time if they are running during the update. It is developed only by Canonical and their IoT division is the driver. The Desktop division has little focus on it. Their Software Center was barely working for years. Flatpak, in comparison, has a thriving community. Every non-Ubuntu distro is focused on it and all XDG features appear there first. Flathub grows and improves every day. But you also can have your own store (like some distros do). And there are nice GUI apps like Flatseal and Warehouse to mange your packages. Also, people from Flatpak are active on GitHub and help projects which require not yet supported features.

**Comment by ebits21** [comment]
I would also echo the sentiment for flatpak over snap (but both are fine).

Flatpak is a bit more universal in support across distros as shipped (such as Fedora), snap being mostly pushed just by Ubuntu.

**Comment by maxfridbe** [comment]
I came here to ask for flatpak as well (snaps dont work well off of ubuntu) im on fedora.

**Comment by maxfridbe** [comment]
> I came to request this as well. 🙂
> 
> I use Fedora Silverblue and would rather not layer anything (or if it doesn't need layered, have to manually update things).

Exact same.

**Comment by BinaryBytecode** [comment]
Flatpaks! It works on almost all distros so I think it's a good idea, then it would be good to have it on AUR, apt, portage and all the other package managers.

**Comment by gitvalds** [comment]
> Flatpaks! It works on almost all distros so I think it's a good idea, then it would be good to have it on AUR, apt, portage and all the other package managers.

The whole point of packaging with flatpak (or snap, which I don't like) is not having to package it differently for each distribution.
There are minor limitations compared to the packaging of the distributions, but the advantage for the developers and for the users (which have applications which they would not have), is way bigger than those limitations.

**Comment by gonzolively** [comment]
flatpack vote

**Comment by PylotLight** [comment]
How is this legacy? You have the worse packaging format appimage vs the superior flatpak? Whats that about?

**Comment by esimkowitz** [comment]
Closing in favor of #1092 and #1091
