### ISSUE TITLE
Error launching app

### ISSUE THREAD

**Issue by unlux** [wavetermdev/waveterm#713]
**Describe the bug**
waveterm installed using paru(tried with pacman too) on fresh Arch Linux install, i get the following error

```
❯ waveterm
Error launching app
Unable to find Electron app at /usr/lib/waveterm/app

Cannot find module '/usr/lib/waveterm/app'
```

**To Reproduce**
1. open terminal
2. type waveterm 
3. press enter.

**Expected behavior**
Wave terminal opens

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Latest Arch Linux on X86_64 with latest linux kernel

**Comment by damadorPL** [comment]
pkgbuild is broken for arch

go to https://www.waveterm.dev/download  download pacman package and use 

sudo pacmam /path/to/file/file.pacman

dont update it via paru/yay/pacman from repo util its fixed

**Comment by unlux** [comment]
alright.

**Comment by GodSpoon** [comment]
Quick script/instructions for arch/endeavouros users
```
e() { echo -e "\n- $* -\n"; }

e "Download the latest WaveTerm package"
wget -q --show-progress $(curl -s https://www.waveterm.dev/download | grep -oP 'href="\K(https?:)?//[^"]*\.pacman' | sed 's,^//,https://,' | sort -V | tail -n 1)

e "Install WaveTerm package"
sudo pacman -U Wave-linux-x64-.pacman 

e "Add an IgnorePkg entry to pacman.conf to ignore WaveTerm updates"
sudo grep -q '^IgnorePkg = waveterm' /etc/pacman.conf || sudo sed -i '/^\[options\]/a IgnorePkg = waveterm' /etc/pacman.conf && echo -e "\nAdded line:" && grep "IgnorePkg = waveterm" /etc/pacman.conf

e "Remove package file"
rm Wave-linux*.pacman && echo "✔️" && unset -f e
```
