### ISSUE TITLE
Suggestions for making the UI more minimal

### ISSUE THREAD

**Issue by stianst** [wavetermdev/waveterm#73]
**Is your feature request related to a problem? Please describe.**
The Wave Terminal has great potential, and brings a fresh and innovative approach to terminal emulators. However, for an application used by developers on a daily basis a more minimal UI with less distracting elements would be beneficial. The more space that is available to terminal input and output the better.

**Describe the solution you'd like**
Here's a few proposal I believe could make the Wave Terminal even better than it is today.

Consider removing the left side-bar menu as this takes a fair bit of horizontal screen estate.  Or, at least make it more minimal when hidden. As shown in the following image when minimized it is still taking quite a few pixels of the width:

![image](https://github.com/wavetermdev/waveterm/assets/2271511/b46f4650-682d-40e7-9a37-7772fe367c4b)

Provide better integration with Gnome and remove the "Wave  File  Edit  ..." bar. As an example compare Gnome Terminal to Wave:

![image](https://github.com/wavetermdev/waveterm/assets/2271511/8eeaf046-8745-4ecd-b47b-e46e4b2da49d)
![image](https://github.com/wavetermdev/waveterm/assets/2271511/af06eb0d-81f3-443c-853f-fdbfe91eadb3)

Consider removing Documentation and Discord, or moving to the application menu. The majority of developers do not need to see these links on a daily basis

Workspaces are a great feature, but I wonder if it would be better to have these at the top above the tabs for each workspace. That could bring a more minimal view, and also make it more seamless to switch between workspaces and tabs.

**Comment by sawka** [comment]
Thanks for submitting the issue!

* Understand about the left bar.  Working on some UI mockups to make the left bar disappear
* Agree about the menus + title bar.  We were able to remove those on Mac, but we'll have to do some digging to figure out how to get rid of them on Linux
* Not sure about workspaces on top -- I think it will be too confusing to have two sets of tabs.  But, we do want to create an easier way to switch between tabs/workspaces (like Cmd-P in VSCode).  You can also switch workspaces using the keyboard shortcut: Cmd-Ctrl-[num].

**Comment by stianst** [comment]
Sounds good, and yeah not convinced about workspace on top either. Would still be nice to have a way to easily view/navigate to them without the left bar. Keyboard shortcuts are great, but when the left menu is hidden I can';t currently see what workspace I'm on. Would a drop-down next to the tabs make sense?
