### ISSUE TITLE
[DOCS] Link to introduction fails

### ISSUE THREAD

**Issue by mroeling** [wavetermdev/waveterm#74]
**Describe the bug**
https://docs.waveterm.dev/introduction Link to introduction is failing

**To Reproduce**
1. Go to documentation: https://docs.waveterm.dev/quickstart
2. Click on 'Introduction'

**Expected behavior**
Working documentation page

**Screenshots**
![image](https://github.com/wavetermdev/waveterm/assets/2706186/de8daf7d-2d29-4de7-b810-f4de51090eeb)

**Desktop (please complete the following information):**
Ubuntu 23.10, any browser

**Additional context**
Error 500, indication of backend error

**Comment by sawka** [comment]
Thanks for reporting!  Working on a fix

**Comment by tracymiranda** [comment]
This is now fixed: https://github.com/wavetermdev/waveterm-docs/pull/3
