### ISSUE TITLE
Support for fish shell ?

### ISSUE THREAD

**Issue by HiIamChaitanya** [wavetermdev/waveterm#742]
I've been using fish shell as my default long time now and I believe it is a much better implementation than Bash or Zsh. It is faster, easier to use, hence more efficient, and has many great features. I'm not sure if this project is currently considering supporting fish shell.

**Comment by jokeyrhyme** [comment]
Could be tackled by #144  ?

**Comment by jokeyrhyme** [comment]
Similar to #91  ?
