### ISSUE TITLE
Ikarus marks waveterm-...-v0.5.0.dmg as PUA.OSX.Adware (VirusTotal report)

### ISSUE THREAD

**Issue by andrei-akopian** [wavetermdev/waveterm#79]
https://www.virustotal.com/gui/file/94dff6a2f50c0cec32a9e42e1edd47bb3a93ecf2d1f929004fb4928d03c16a28

Probably false positive, but I will still leave it here.

Also, I recommend uploading all binaries to VirusTotal to make the project look more checked and popular.

Anyway, I am a newbie and I won't pretend any of this is relevant.

**Comment by sawka** [comment]
Thanks for posting.  Not sure why anything is getting flagged.  The MacOS build is signed and notarized by Apple (which checks it for malware).  Good info on the site though, will try to look into it.

**Comment by sawka** [comment]
I'm going to mark it as "invalid" because given Apple is already checking for malware (and we of course aren't adding any!), I'm pretty sure this is a false positive.  Leaving it open for now though until we research it a bit (and hopefully figure out how to get the warning removed).
