### ISSUE TITLE
How to delete a connections ?

### ISSUE THREAD

**Issue by YanxinNet** [wavetermdev/waveterm#82]
I can not find a place to delete a connec in connections list？Is it has this function ？

**Comment by sawka** [comment]
Yes, go to the connection, and click on "edit connection settings".  Then you can click "Archive Connection".  This will delete all of the connection information (key, password, alias, etc.) and remove it from the connection list.

**Comment by YanxinNet** [comment]
Thank you!

**Comment by YanxinNet** [comment]
> Yes, go to the connection, and click on "edit connection settings". Then you can click "Archive Connection". This will delete all of the connection information (key, password, alias, etc.) and remove it from the connection list.

Thank you!
