### ISSUE TITLE
FEAT REQUEST: Add arg version to show the version

### ISSUE THREAD

**Issue by bagustris** [wavetermdev/waveterm#845]
**Is your feature request related to a problem? Please describe.**
To check the current version, I need several clicks, at least: open waveterm >> three dots >> wave >> about wave terminal

**Describe the solution you'd like**
Just command line version, that is
``` 
$ waveterm --version
Client Version 0.8.3-beta.10 (202409250607)
Update Channel: beta
```
would be simpler.

**Comment by sawka** [comment]
ah, you can use `wsh version` to show the version on the CLI
