### ISSUE TITLE
Default shell setting for Windows

### ISSUE THREAD

**Issue by esimkowitz** [wavetermdev/waveterm#856]
**Is your feature request related to a problem? Please describe.**

On Mac and Linux, we honor the `chsh` settings for determining which shell to use. On Windows, we only support Windows Powershell.

**Describe the solution you'd like**

We should let users specify the default shell to use on Windows, including setting it to WSL, Cygwin, Git Bash, MSYS2, etc.

We can treat this somewhat like a remote, so that we don't need to relaunch the VM for each command, but we can make use of the filesystem access to use the installed WSH version, rather than needing to copy it over.

We should also support other native shells like Powershell Core and Command Prompt, though the latter is probably difficult just because it sucks (syntactically :P)

**Comment by C0sm0cats** [comment]
I completely agree with this suggestion! I would love to be able to use Git Bash on Windows. Having the option to set a default shell would be a significant improvement, especially for those of us who prefer development tools like Git Bash. It would enhance the user experience on Windows and provide a more consistent working environment. Thanks for considering this feature!

**Comment by esimkowitz** [comment]
WSL is being worked on currently, @oneirocosm can provide more details. Git-Bash, MSYS2, Docker, are also on our radar, as are AWS, Azure, and GCloud shells. Any others I'm missing?

**Comment by C0sm0cats** [comment]
As an Arch Linux user, I value having my default shell (Zsh), and for work, I rely on the Windows version. I fully support the idea of adding options for users to select their preferred shell, like Git Bash or WSL, as it would greatly enhance the overall experience. A more flexible environment would truly benefit developers.

@esimkowitz, it’s great to hear that other shells are being considered. Let’s also explore user-defined settings for even more customization. We could implement a setting that allows users to specify the path to their preferred shell. Alongside this, a toggle could enable users to easily switch between different shells. This combination would provide the flexibility to create a personalized environment that aligns with each developer's workflow.

I’m excited to see what other shells users are interested in! Let’s keep the conversation going and see what other shells users are interested in!

**Comment by sawka** [comment]
we have a new config setting `term:localshellpath` (and the associated `term:localshellopts`) (see https://docs.waveterm.dev/config).

not closing this yet though since we want to make sure, as much as possible, that we also get `wsh` added to the path even when using a custom shell.

we're making progress on native WSL.  hope to get that feature out shortly.

**Comment by C0sm0cats** [comment]
Hi @sawka,

I tested the new config setting term:localshellpath on Manjaro by switching from zsh to sh, and on Windows, where I was able to switch to Git Bash instead of the default PowerShell. Everything is working perfectly, thank you!
