### ISSUE TITLE
No dots in ssh username supported

### ISSUE THREAD

**Issue by Zigu** [wavetermdev/waveterm#87]
**Describe the bug**
When I want to create an SSH connection and use a username with dot (e.g. robert.porscha) I get an error message, that the argument has an invalid format.

**To Reproduce**
1. Go to 'Connections'
2. Click on 'Add SSH connection'
3. Enter 'robert.porscha@sshhost' (hostname does not matter) in "user@host" field
4. Click on "Create Remote"
5. See error "Error: /remote:new invalid format of user@host argument"

**Expected behavior**
I would have expected that any kind of username is supported, as in native ssh command.

**Screenshots**
<img width="643" alt="Bildschirmfoto 2023-11-25 um 14 10 05" src="https://github.com/wavetermdev/waveterm/assets/402066/75ecf799-6369-43cb-8da2-28bd1a445569">

**Desktop (please complete the following information):**
 - OS: MacOS, x64
 - Version: v0.5.0

**Comment by sawka** [comment]
Thanks for submitting!  This is definitely a bug.  Just pushed a fix on our v0.5.1 branch.  Will go out with the next release.

https://github.com/wavetermdev/waveterm/commit/64203e7823ce1ce347726b531028f3aab548f9f0
