### ISSUE TITLE
International Characters Appear as Question Marks

### ISSUE THREAD

**Issue by princox** [wavetermdev/waveterm#88]
**Describe the bug**
When viewing files with the `ls` command, terms other than English are not displayed properly

**Expected behavior**
Korean must be displayed properly

**Screenshots**

<img width="602" alt="스크린샷 2023-11-25 오후 10 47 45" src="https://github.com/wavetermdev/waveterm/assets/8064262/e5be56e9-1340-4eb8-aff8-423be35f2202">

**Desktop (please complete the following information):**
 - OS: MacOS Apple M1 Pro
 - Version: Sonoma 14.1.1

**Additional context**
I'd appreciate it if you could fix it.

**Comment by sawka** [comment]
Thanks for submitting.  We haven't done much testing on international text yet.

**Comment by princox** [comment]
> Thanks for submitting. We haven't done much testing on international text yet.

I would be so happy to be able to use such great software in my native language.

**Comment by wyatt-wong** [comment]
I was surprised that Unicode was not considered in the initial release. That's even worse than the default macOS Terminal.

**Comment by leisefuxX** [comment]
OS: Sonoma 14.2.1 - no unicode characters? UTF-8 not ootb? deal breaker for me. sorry. 
🍺`brew uninstall --cask wave`

**Comment by oneirocosm** [comment]
Closing since this has been fixed with the merge of pull #209. It is available in v0.6.0
