### ISSUE TITLE
Changed code signature in macOS version 0.8.6?

### ISSUE THREAD

**Issue by suschizu** [wavetermdev/waveterm#901]
Since version 0.8.4 the downloaded app has a different code signature:
EXPECTED 'Michael Sawka (8M47V3YG4N)' 
FOUND 'Command Line Inc (M4LA8V687Y)'

can you confirm this? 

codesign -dv --verbose=4 /Path/To/Application.app

MacOS 13.6
https://github.com/wavetermdev/waveterm/releases/download/v0.8.6/Wave-darwin-universal-0.8.6.dmg

**Comment by esimkowitz** [comment]
Hey, yes we changed from signing with @sawka's personal developer account to our corporate developer account with the v0.8.0 release. This is expected. See https://github.com/wavetermdev/waveterm/discussions/900

**Comment by suschizu** [comment]
ok perfect  - thanks for the explanation 🙌
