### ISSUE TITLE
Native title bar not working

### ISSUE THREAD

**Issue by texastoland** [wavetermdev/waveterm#903]
## Describe the bug

`"window:nativetitlebar": true` introduced in #837 doesn't change my title bar. I'm not sure if Mac supports them but transparency, etc. didn't have any effect either.

## Versions

- macOS 15.0 (24A335)
- Wave 0.8.6 (202409262306)

**Comment by esimkowitz** [comment]
Hey, this has no effect on Mac as we already use the native UI elements here. Check out https://docs.waveterm.dev/config for a list of compatibility of various configs https://docs.waveterm.dev/config

**Comment by texastoland** [comment]
Oh I misread it 🙏🏼 I actually used `wsh setconfig`. Maybe it could warn/error on OS mismatch in the future. Thanks again!

**Comment by esimkowitz** [comment]
Ah yeah, we're planning to make the settings flow smarter so it can detect when a setting won't apply and warn you about it
