### ISSUE TITLE
Alt-W doesn't work on Linux

### ISSUE THREAD

**Issue by ToontjeM** [wavetermdev/waveterm#917]
**Describe the bug**
Alt-W is used to close a block. This works on Mac, but not on Ubuntu 22.04. 

**To Reproduce**
1. Open a terminal window.
2. Do something in the terminal.
3. Press Alt-W to close the block.

**Expected behavior**
Block closes.

**Shown behavior**
Block doesn't close.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 AMD64
 - Version: 0.8.7

**Additional context**
I noticed that non-terminal blocks (CPU, AI, Help, Tips, Files) do close.

**Comment by esimkowitz** [comment]
Should be fixed with v0.8.8
