### ISSUE TITLE
Cannot add a SSH connection, keyboard combo not triggering

### ISSUE THREAD

**Issue by Rho-bur** [wavetermdev/waveterm#921]
**Describe the bug**
Cannot add a SSH connection, keyboard combo not triggering

**To Reproduce**
1. Open a terminal tab
2. Use CommandKey+G or ALT+G as described in keyboard combos
3. 
4. Nothing happens.

**Expected behavior**
Expect a dialog to set up the connection parameters.

**Desktop (please complete the following information):**
 - OS: Ubuntu with Budgie desktop
 - Version 24.04

**Additional context**
The Connection page in the documentation is empty

**Comment by esimkowitz** [comment]
I'm not sure I follow, we don't currently have a Cmd+G/Alt+G keybinding, is this a feature request or is something actually broken?

**Comment by esimkowitz** [comment]
Update: ignore me, this is a valid keybinding. Will fix
