### ISSUE TITLE
[Feature]: Add a toggle to switch between the default AI handler and a custom setup

### ISSUE THREAD

**Issue by C0sm0cats** [wavetermdev/waveterm#945]
### Feature description

I would like to propose adding a toggle or a clear UI indicator that allows users to easily switch between the default AI handler and a custom configuration. This feature would enhance the user experience, especially for those who may not be familiar with the technical aspects of setting up their own AI integrations.

### Implementation Suggestion

- **Configuration Storage**:
    - Store the user's preference (default or custom) in user settings.
- **Default AI Handler**:
    - Define a default AI handler that provides a pre-configured AI service or model.
- **Custom AI Handler**:
    - Allow users to input custom configuration details (e.g., API key, endpoint URL) for their preferred AI service or model.
- **Handler Switching**:
    - When the toggle switch is changed:
        - **Default**: Load the pre-configured default AI handler.
        - **Custom**: Load the custom AI handler based on the user's input configuration.

This feature would make it easier for users to manage their AI configurations directly within the AI block, enhancing their confidence in data privacy and control. It aligns with Waveterm’s commitment to user empowerment and transparency.

**Comment by sawka** [comment]
sounds good.  my idea to fix this is to have it work similar to how the meta overrides work for the other blocks.  so we'll have the config file which sets the default options.  but each individual block can have different settings in its metadata.  so in widgets.json you can have quick buttons to open different AI blocks, and we can also make "presets" so you can quickly switch between them.
