### ISSUE TITLE
[Bug]: Better handling of empty and non-existent files with `wsh edit`

### ISSUE THREAD

**Issue by ToontjeM** [wavetermdev/waveterm#947]
### Feature description

Because `wsh edit` doesn´t create new files, a new file needs to be created using the `touch` command. This command creates a 0-byte file. When trying to `wsh edit` this file i get the message `Unable to determine mimetype for: <file>`.

### Implementation Suggestion

The new behavior should be that whenever the MIME type is unknown or a 0-byte file is to be edited, `wsh edit` needs to assume it's a text file.

### Anything else?

Related to https://github.com/wavetermdev/waveterm/issues/925.

**Comment by esimkowitz** [comment]
Fixed with #963
