### ISSUE TITLE
Add support for using ssh config file for connections

### ISSUE THREAD

**Issue by kevinCDW** [wavetermdev/waveterm#95]
While using wave terminal, you have to set up the details of each connection in the interface. If you've already defined the connections in your ~/.ssh/config file, they have to be reentered.
Would be a great feature to have it already fill out the connections(could be opt in too) with what is in the ssh config file.

**Comment by oneirocosm** [comment]
I will be adding more features to this in the future, but the basic functionality is present in v0.7.0
