### ISSUE TITLE
[Bug]: cursorAccent color property seems not working.

### ISSUE THREAD

**Issue by geekgao** [wavetermdev/waveterm#967]
### Current Behavior

Edit the theme config, change the cursorAccent can not change the color of the cursor

### Expected Behavior

Change color

### Steps To Reproduce

create or  edit config file ~/.waveterm/config/termthemes.json

` "Solarized-Light": {
            "display:name": "Solarized Light",
            "background": "#f2dea5",
            "foreground": "#657B83",
            "cursorAccent": "#073642",
            "selectionBackground": "#EEE8D5",
            "black": "#073642",
            "red": "#DC322F",
            "green": "#859900",
            "yellow": "#B58900",
            "blue": "#268BD2",
            "magenta": "#D33682",
            "cyan": "#2AA198",
            "white": "#EEE8D5",
            "brightBlack": "#002B36",
            "brightRed": "#CB4B16",
            "brightGreen": "#586E75",
            "brightYellow": "#657B83",
            "brightBlue": "#839496",
            "brightMagenta": "#6C71C4",
            "brightCyan": "#93A1A1",
            "brightWhite": "#FDF6E3",
            "cmdtext": "#abb2bf"	
        }`

### Wave Version

v0.8.8

### Architecture

x64

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [X] I don't have time to fix this right now, but maybe later

**Comment by geekgao** [comment]
I see through the source code that xtermjs has a cursor color property of[cursor](https://xtermjs.org/docs/api/terminal/interfaces/itheme/#optional-cursor)
  So I add this property to config file,  but it seems not loading this property on combinedTheme in source file:  termtheme.ts

**Comment by geekgao** [comment]
Append: I  change the source code , and added cursor property. It works now.
So, Could I request a PR ?

**Comment by sawka** [comment]
thanks for reporting!  just fixed it in the source.  changed cursorAccent -> cursor (also set for the current themes):
https://github.com/wavetermdev/waveterm/pull/968
