### ISSUE TITLE
Connect failed because remote server doesn't have GLIBC dependency

### ISSUE THREAD

**Issue by abserari** [wavetermdev/waveterm#98]
**Describe the bug**
prompt> error connecting to remote: invalid packet received from mshell client: raw[mshell-v0.3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by mshell-v0.3)]
prompt> error reading from controlling-pty: read /dev/ptmx: input/output error

**To Reproduce**
1. Go to Connections
2. Click on install
3. Scroll down to prompt

**Expected behavior**
connect success.

**Screenshots**
![图片](https://github.com/wavetermdev/waveterm/assets/32089134/50fb38fa-33a7-47a0-b30f-c658259a97d7)

**Desktop (please complete the following information):**
 - OS: [Linux, x64]
 - Version [v0.5.0]

**Additional context**
The remote server indeed has not the regular glibc.

**Comment by sawka** [comment]
Ah, same issue as https://github.com/wavetermdev/waveterm/issues/89 (although this affects waveshell not wavesrv) .  Will close as a duplicate.  Need to update our golang builds to not depend on this version of glibc.
