### ISSUE TITLE
[Feature]: Github flavoured makrdown support along with mermaid support

### ISSUE THREAD

**Issue by its-19818942118** [wavetermdev/waveterm#983]
### Feature description

so from my experience of using wave term. i have found that github markdown syntax inst valid.
what do i mean by this? well when doing
> [!NOTE]
> this works.

but not on file preview of wave
![image](https://github.com/user-attachments/assets/86cc2c38-dbb0-4a1d-967a-302025cfa8e5)
the syntax
![image](https://github.com/user-attachments/assets/78846e42-4e2c-4934-b362-6476217a5138)

this doesnt have the github markdown support. mermaid support isnt there too 

### Implementation Suggestion

well adding support for github markdown and mermaid and any other markdown support helps :smile: 
much appreciated.

**Comment by esimkowitz** [comment]
Fixed the GH alerts parsing with #988. I'm going to mark Mermaid as won't fix for now because the Rehype library for parsing it requires Playwright, which is a really beefy library

**Comment by its-19818942118** [comment]
> Fixed the GH alerts parsing with #988. I'm going to mark Mermaid as won't fix for now because the Rehype library for parsing it doubles our JS bundle size. We'll address this when we add extensions, but for now it's out of scope

thanks for letting me know
